; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35208.0 

	TITLE	C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_NothingToSeeHere
PUBLIC	__fltused
PUBLIC	_EnableTheAncientChaosGods
PUBLIC	_GodCheck
PUBLIC	_THEZERO
PUBLIC	_KillACertainPolititianThatIsA
PUBLIC	_VgaMemoryAddress
_BSS	SEGMENT
_EnableTheAncientChaosGods DD 01H DUP (?)
_BSS	ENDS
_DATA	SEGMENT
_NothingToSeeHere DD 01H
__fltused DD	09875H
_GodCheck DD	FLAT:$SG30418
_KillACertainPolititianThatIsA DD FLAT:$SG30421
$SG30418 DB	'works ig? and The most important variable is set to: {in'
	DB	't:NothingToSeeHere}', 00H
_THEZERO DB	01H
	DB	01H
	DB	03cH
	DB	066H
	DB	0cbH
	DB	0cbH
	DB	0cbH
	DB	0d3H
	DB	0d3H
	DB	0d3H
	DB	066H
	DB	03cH
	DB	040H
	DB	040H
	DB	00H
	DB	00H
$SG30421 DB	'Racist, orange, sex offender and an idiotic Idiot. ', 00H
_VgaMemoryAddress DD 0b8000H
_DATA	ENDS
PUBLIC	_NothingElseToSeeHere
PUBLIC	_KernelPrintCharacter
PUBLIC	_kprint
PUBLIC	_kprint_int
PUBLIC	_kprintf
PUBLIC	_SetCursorPosition
PUBLIC	_SetCursorAndColor
PUBLIC	_DrawLayoutBox
PUBLIC	_DrawLayout
PUBLIC	_UnderscoreCursorGoesHereAt
PUBLIC	_RedrawCedLineNumbers
PUBLIC	_ScrollCed
PUBLIC	_ExecuteNavCommand
PUBLIC	_TypeChar
PUBLIC	_KeyboardDriver
PUBLIC	_LOADTHEZERO
PUBLIC	_main
PUBLIC	__real@40c3880000000000
PUBLIC	__xmm@80000000000000008000000000000000
EXTRN	__fltused:DWORD
_BSS	SEGMENT
_OvertypeMode DD 01H DUP (?)
_BitCount DD	01H DUP (?)
_InsertHeld DD	01H DUP (?)
_InsertTimer DD	01H DUP (?)
_VgaBufferIndex DD 01H DUP (?)
_BSS	ENDS
;	COMDAT __xmm@80000000000000008000000000000000
CONST	SEGMENT
__xmm@80000000000000008000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __real@40c3880000000000
CONST	SEGMENT
__real@40c3880000000000 DQ 040c3880000000000r	; 10000
CONST	ENDS
_DATA	SEGMENT
_LeftX	DD	04H
_LeftY	DD	07H
_RightX	DD	036H
_RightY	DD	07H
_ActiveBox DD	01H
_CedBaseLine DD	01H
_NavCmdStartY DD 07H
_NavCmdStartX DD 036H
_CurrentTextColor DB 07H
	ORG $+3
$SG30445 DB	'LOCATOR', 00H
$SG30446 DB	'Racist, orange, sex offender and an idiotic Idiot. ', 00H
$SG30574 DB	'str:', 00H
	ORG $+3
$SG30577 DB	'int:', 00H
	ORG $+3
$SG30580 DB	'flo:', 00H
	ORG $+3
$SG30725 DB	'clear CED', 00H
	ORG $+2
$SG30728 DB	'clear NAV', 00H
	ORG $+2
$SG30731 DB	'run CED', 00H
$SG30738 DB	'jmp mcrs,row ', 00H
	ORG $+2
$SG30741 DB	'jmp mcrs,col ', 00H
	ORG $+2
$SG30826 DB	' I hope you memorized the ASCII and Opcode tables.', 00H
	ORG $+1
$SG30827 DB	'Because, if you want complete control over your computer'
	DB	' you''ll need it.', 00H
	ORG $+3
$SG30828 DB	'< ', 0ffH, 'OS >', 00H
$SG30829 DB	'[Slightly better than Windows!]', 00H
$SG30830 DB	'CED', 00H
$SG30831 DB	'NAV', 00H
_DATA	ENDS
voltbl	SEGMENT
_volmd	DD	0ffffffffH
	DDSymXIndex: 	FLAT:_LOADTHEZERO
	DD	0aaH
_volmd	DD	0ffffffffH
	DDSymXIndex: 	FLAT:_DrawLayout
	DD	037H
	DD	054H
_volmd	DD	0ffffffffH
	DDSymXIndex: 	FLAT:_KernelPrintCharacter
	DD	03cH
	DD	05dH
_volmd	DD	0ffffffffH
	DDSymXIndex: 	FLAT:_TypeChar
	DD	059H
	DD	05cH
	DD	06cH
	DD	076H
_volmd	DD	0ffffffffH
	DDSymXIndex: 	FLAT:_KeyboardDriver
	DD	02d0H
	DD	02d2H
	DD	02ddH
	DD	048dH
	DD	048fH
	DD	049aH
_volmd	DD	0ffffffffH
	DDSymXIndex: 	FLAT:_ExecuteNavCommand
	DD	0b4H
	DD	018bH
	DD	0197H
	DD	0225H
	DD	0231H
	DD	02d3H
_volmd	DD	0ffffffffH
	DDSymXIndex: 	FLAT:_ScrollCed
	DD	071H
	DD	073H
	DD	086H
	DD	089H
	DD	0beH
	DD	0c9H
voltbl	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 661
	push	ebp
	mov	ebp, esp
; Line 662
	call	_NothingElseToSeeHere
; Line 664
	cmp	DWORD PTR _NothingToSeeHere, 1
	jne	$LN3@main
; Line 665
	call	_NothingElseToSeeHere
; Line 667
	push	255					; 000000ffH
	push	OFFSET _THEZERO
	call	_LOADTHEZERO
	add	esp, 8
; Line 670
	call	_DrawLayout
; Line 672
	push	15					; 0000000fH
	push	1
	push	14					; 0000000eH
	call	_SetCursorAndColor
	add	esp, 12					; 0000000cH
	push	OFFSET $SG30826
	call	_kprintf
	add	esp, 4
; Line 673
	push	15					; 0000000fH
	push	2
	push	4
	call	_SetCursorAndColor
	add	esp, 12					; 0000000cH
	push	OFFSET $SG30827
	call	_kprintf
	add	esp, 4
; Line 674
	push	5
	push	4
	push	37					; 00000025H
	call	_SetCursorAndColor
	add	esp, 12					; 0000000cH
	push	OFFSET $SG30828
	call	_kprintf
	add	esp, 4
; Line 675
	push	14					; 0000000eH
	push	4
	push	47					; 0000002fH
	call	_SetCursorAndColor
	add	esp, 12					; 0000000cH
	push	OFFSET $SG30829
	call	_kprintf
	add	esp, 4
; Line 676
	push	15					; 0000000fH
	push	23					; 00000017H
	push	1
	call	_SetCursorAndColor
	add	esp, 12					; 0000000cH
	push	OFFSET $SG30830
	call	_kprintf
	add	esp, 4
; Line 677
	push	15					; 0000000fH
	push	23					; 00000017H
	push	51					; 00000033H
	call	_SetCursorAndColor
	add	esp, 12					; 0000000cH
	push	OFFSET $SG30831
	call	_kprintf
	add	esp, 4
; Line 679
	mov	eax, DWORD PTR _LeftY
	push	eax
	mov	ecx, DWORD PTR _LeftX
	push	ecx
	call	_UnderscoreCursorGoesHereAt
	add	esp, 8
$LN2@main:
; Line 681
	mov	edx, 1
	test	edx, edx
	je	SHORT $LN3@main
; Line 682
	call	_KeyboardDriver
	npad	1
; Line 683
	jmp	SHORT $LN2@main
$LN3@main:
; Line 685
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_FontPtBORINGASSSH_T$ = -8				; size = 4
_i$1 = -4						; size = 4
_bitmap$ = 8						; size = 4
_CharIndex$ = 12					; size = 4
_LOADTHEZERO PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 622
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 625
	mov	edx, 964				; 000003c4H
	xor	al, al
	out	dx, al
	mov	edx, 965				; 000003c5H
	mov	al, 1
	out	dx, al
; Line 626
	mov	edx, 964				; 000003c4H
	mov	al, 2
	out	dx, al
	mov	edx, 965				; 000003c5H
	mov	al, 4
	out	dx, al
; Line 627
	mov	edx, 964				; 000003c4H
	mov	al, 4
	out	dx, al
	mov	edx, 965				; 000003c5H
	mov	al, 7
	out	dx, al
; Line 628
	mov	edx, 964				; 000003c4H
	xor	al, al
	out	dx, al
	mov	edx, 965				; 000003c5H
	mov	al, 3
	out	dx, al
; Line 630
	mov	edx, 974				; 000003ceH
	mov	al, 4
	out	dx, al
	mov	edx, 975				; 000003cfH
	mov	al, 2
	out	dx, al
; Line 631
	mov	edx, 974				; 000003ceH
	mov	al, 5
	out	dx, al
	mov	edx, 975				; 000003cfH
	xor	al, al
	out	dx, al
; Line 632
	mov	edx, 974				; 000003ceH
	mov	al, 6
	out	dx, al
	mov	edx, 975				; 000003cfH
	xor	al, al
	out	dx, al
; Line 638
	mov	eax, DWORD PTR _CharIndex$[ebp]
	shl	eax, 5
	add	eax, 655360				; 000a0000H
	mov	DWORD PTR _FontPtBORINGASSSH_T$[ebp], eax
; Line 639
	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN4@LOADTHEZER
$LN2@LOADTHEZER:
	mov	ecx, DWORD PTR _i$1[ebp]
	add	ecx, 1
	mov	DWORD PTR _i$1[ebp], ecx
$LN4@LOADTHEZER:
	cmp	DWORD PTR _i$1[ebp], 16			; 00000010H
	jge	SHORT $LN3@LOADTHEZER
; Line 640
	mov	edx, DWORD PTR _FontPtBORINGASSSH_T$[ebp]
	add	edx, DWORD PTR _i$1[ebp]
	mov	eax, DWORD PTR _bitmap$[ebp]
	add	eax, DWORD PTR _i$1[ebp]
	mov	cl, BYTE PTR [eax]
	mov	BYTE PTR [edx], cl
; Line 641
	jmp	SHORT $LN2@LOADTHEZER
$LN3@LOADTHEZER:
; Line 646
	mov	edx, 964				; 000003c4H
	xor	al, al
	out	dx, al
	mov	edx, 965				; 000003c5H
	mov	al, 1
	out	dx, al
; Line 647
	mov	edx, 964				; 000003c4H
	mov	al, 2
	out	dx, al
	mov	edx, 965				; 000003c5H
	mov	al, 3
	out	dx, al
; Line 648
	mov	edx, 964				; 000003c4H
	mov	al, 4
	out	dx, al
	mov	edx, 965				; 000003c5H
	mov	al, 3
	out	dx, al
; Line 649
	mov	edx, 964				; 000003c4H
	xor	al, al
	out	dx, al
	mov	edx, 965				; 000003c5H
	mov	al, 3
	out	dx, al
; Line 651
	mov	edx, 974				; 000003ceH
	mov	al, 4
	out	dx, al
	mov	edx, 975				; 000003cfH
	xor	al, al
	out	dx, al
; Line 652
	mov	edx, 974				; 000003ceH
	mov	al, 5
	out	dx, al
	mov	edx, 975				; 000003cfH
	mov	al, 16					; 00000010H
	out	dx, al
; Line 653
	mov	edx, 974				; 000003ceH
	mov	al, 6
	out	dx, al
	mov	edx, 975				; 000003cfH
	mov	al, 14					; 0000000eH
	out	dx, al
; Line 655
	mov	esp, ebp
	pop	ebp
	ret	0
_LOADTHEZERO ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_dst$1 = -104						; size = 4
_dst$2 = -100						; size = 4
_src$3 = -96						; size = 4
tv187 = -92						; size = 4
tv185 = -88						; size = 4
tv183 = -84						; size = 4
tv181 = -80						; size = 4
_src$4 = -76						; size = 4
tv136 = -72						; size = 4
tv134 = -68						; size = 4
tv132 = -64						; size = 4
tv130 = -60						; size = 4
tv84 = -56						; size = 4
tv82 = -52						; size = 4
tv80 = -48						; size = 4
_maxX$5 = -44						; size = 4
_maxX$6 = -40						; size = 4
_minX$7 = -36						; size = 4
_minX$8 = -32						; size = 4
_curX$9 = -28						; size = 4
_i$10 = -24						; size = 4
_curX$11 = -20						; size = 4
_i$12 = -16						; size = 4
_curY$13 = -12						; size = 4
_curY$14 = -8						; size = 4
_Scancode$15 = -1					; size = 1
_KeyboardDriver PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 522
	push	ebp
	mov	ebp, esp
	sub	esp, 104				; 00000068H
; Line 523
	mov	edx, 100				; 00000064H
	in	al, dx
	movzx	eax, al
	and	eax, 1
	je	$LN34@KeyboardDr
; Line 524
	mov	edx, 96					; 00000060H
	in	al, dx
	mov	BYTE PTR _Scancode$15[ebp], al
; Line 526
	movzx	ecx, BYTE PTR _Scancode$15[ebp]
	cmp	ecx, 224				; 000000e0H
	jne	SHORT $LN9@KeyboardDr
	cmp	DWORD PTR _NothingToSeeHere, 1
	jne	SHORT $LN9@KeyboardDr
	jmp	$LN35@KeyboardDr
$LN9@KeyboardDr:
; Line 528
	movzx	edx, BYTE PTR _Scancode$15[ebp]
	cmp	edx, 82					; 00000052H
	jne	$LN10@KeyboardDr
	cmp	DWORD PTR _NothingToSeeHere, 1
	jne	$LN10@KeyboardDr
; Line 529
	cmp	DWORD PTR _InsertHeld, 0
	jne	$LN14@KeyboardDr
; Line 530
	mov	DWORD PTR _InsertHeld, 1
; Line 531
	cmp	DWORD PTR _InsertTimer, 0
	jle	SHORT $LN13@KeyboardDr
; Line 532
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN37@KeyboardDr
	mov	DWORD PTR tv80[ebp], 1
	jmp	SHORT $LN38@KeyboardDr
$LN37@KeyboardDr:
	mov	DWORD PTR tv80[ebp], 0
$LN38@KeyboardDr:
	mov	eax, DWORD PTR tv80[ebp]
	mov	DWORD PTR _ActiveBox, eax
; Line 533
	mov	DWORD PTR _InsertTimer, 0
; Line 534
	cmp	DWORD PTR _OvertypeMode, 0
	jne	SHORT $LN39@KeyboardDr
	mov	DWORD PTR tv82[ebp], 1
	jmp	SHORT $LN40@KeyboardDr
$LN39@KeyboardDr:
	mov	DWORD PTR tv82[ebp], 0
$LN40@KeyboardDr:
	mov	ecx, DWORD PTR tv82[ebp]
	mov	DWORD PTR _OvertypeMode, ecx
; Line 535
	mov	DWORD PTR _BitCount, 0
; Line 536
	jmp	SHORT $LN14@KeyboardDr
$LN13@KeyboardDr:
; Line 537
	cmp	DWORD PTR _OvertypeMode, 0
	jne	SHORT $LN41@KeyboardDr
	mov	DWORD PTR tv84[ebp], 1
	jmp	SHORT $LN42@KeyboardDr
$LN41@KeyboardDr:
	mov	DWORD PTR tv84[ebp], 0
$LN42@KeyboardDr:
	mov	edx, DWORD PTR tv84[ebp]
	mov	DWORD PTR _OvertypeMode, edx
; Line 538
	mov	DWORD PTR _InsertTimer, 80000		; 00013880H
$LN14@KeyboardDr:
; Line 540
	jmp	$LN32@KeyboardDr
$LN10@KeyboardDr:
; Line 541
	movzx	eax, BYTE PTR _Scancode$15[ebp]
	cmp	eax, 210				; 000000d2H
	jne	SHORT $LN15@KeyboardDr
	cmp	DWORD PTR _NothingToSeeHere, 1
	jne	SHORT $LN15@KeyboardDr
; Line 542
	mov	DWORD PTR _InsertHeld, 0
	jmp	$LN32@KeyboardDr
$LN15@KeyboardDr:
; Line 543
	movzx	ecx, BYTE PTR _Scancode$15[ebp]
	cmp	ecx, 2
	jne	$LN17@KeyboardDr
	cmp	DWORD PTR _NothingToSeeHere, 1
	jne	$LN17@KeyboardDr
; Line 544
	cmp	DWORD PTR _InsertHeld, 0
	je	SHORT $LN19@KeyboardDr
; Line 545
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN21@KeyboardDr
; Line 546
	call	_ExecuteNavCommand
; Line 547
	cmp	DWORD PTR _RightX, 54			; 00000036H
	jne	SHORT $LN24@KeyboardDr
	cmp	DWORD PTR _RightY, 7
	je	SHORT $LN23@KeyboardDr
$LN24@KeyboardDr:
; Line 548
	mov	edx, DWORD PTR _RightY
	add	edx, 1
	mov	DWORD PTR _RightY, edx
	mov	DWORD PTR _RightX, 54			; 00000036H
$LN23@KeyboardDr:
; Line 550
	mov	eax, DWORD PTR _RightY
	mov	DWORD PTR _NavCmdStartY, eax
; Line 551
	mov	ecx, DWORD PTR _RightX
	mov	DWORD PTR _NavCmdStartX, ecx
; Line 552
	jmp	SHORT $LN22@KeyboardDr
$LN21@KeyboardDr:
; Line 553
	mov	edx, DWORD PTR _LeftY
	add	edx, 1
	mov	DWORD PTR _LeftY, edx
	mov	DWORD PTR _LeftX, 4
; Line 554
	call	_ScrollCed
	npad	1
$LN22@KeyboardDr:
; Line 556
	mov	DWORD PTR _BitCount, 0
; Line 557
	jmp	$LN27@KeyboardDr
$LN19@KeyboardDr:
; Line 558
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN43@KeyboardDr
	mov	DWORD PTR tv130[ebp], OFFSET _RightX
	jmp	SHORT $LN44@KeyboardDr
$LN43@KeyboardDr:
	mov	DWORD PTR tv130[ebp], OFFSET _LeftX
$LN44@KeyboardDr:
	mov	eax, DWORD PTR tv130[ebp]
	mov	DWORD PTR _curX$11[ebp], eax
; Line 559
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN45@KeyboardDr
	mov	DWORD PTR tv132[ebp], OFFSET _RightY
	jmp	SHORT $LN46@KeyboardDr
$LN45@KeyboardDr:
	mov	DWORD PTR tv132[ebp], OFFSET _LeftY
$LN46@KeyboardDr:
	mov	ecx, DWORD PTR tv132[ebp]
	mov	DWORD PTR _curY$14[ebp], ecx
; Line 560
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN47@KeyboardDr
	mov	DWORD PTR tv134[ebp], 54		; 00000036H
	jmp	SHORT $LN48@KeyboardDr
$LN47@KeyboardDr:
	mov	DWORD PTR tv134[ebp], 4
$LN48@KeyboardDr:
	mov	edx, DWORD PTR tv134[ebp]
	mov	DWORD PTR _minX$8[ebp], edx
; Line 561
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN49@KeyboardDr
	mov	DWORD PTR tv136[ebp], 79		; 0000004fH
	jmp	SHORT $LN50@KeyboardDr
$LN49@KeyboardDr:
	mov	DWORD PTR tv136[ebp], 49		; 00000031H
$LN50@KeyboardDr:
	mov	eax, DWORD PTR tv136[ebp]
	mov	DWORD PTR _maxX$6[ebp], eax
; Line 563
	mov	ecx, DWORD PTR _curX$11[ebp]
	mov	edx, DWORD PTR [ecx]
	add	edx, 8
	sub	edx, DWORD PTR _BitCount
	cmp	edx, DWORD PTR _maxX$6[ebp]
	jl	$LN25@KeyboardDr
; Line 564
	mov	eax, DWORD PTR _curY$14[ebp]
	mov	ecx, DWORD PTR [eax]
	add	ecx, 1
	mov	edx, DWORD PTR _curY$14[ebp]
	mov	DWORD PTR [edx], ecx
; Line 565
	cmp	DWORD PTR _curY$14[ebp], OFFSET _LeftY
	jne	SHORT $LN26@KeyboardDr
	call	_ScrollCed
	npad	1
$LN26@KeyboardDr:
; Line 567
	mov	DWORD PTR _i$12[ebp], 0
	jmp	SHORT $LN4@KeyboardDr
$LN2@KeyboardDr:
	mov	eax, DWORD PTR _i$12[ebp]
	add	eax, 1
	mov	DWORD PTR _i$12[ebp], eax
$LN4@KeyboardDr:
	mov	ecx, DWORD PTR _i$12[ebp]
	cmp	ecx, DWORD PTR _BitCount
	jge	SHORT $LN3@KeyboardDr
; Line 568
	mov	edx, DWORD PTR _curY$14[ebp]
	mov	eax, DWORD PTR [edx]
	sub	eax, 1
	imul	ecx, eax, 80
	mov	edx, DWORD PTR _curX$11[ebp]
	add	ecx, DWORD PTR [edx]
	sub	ecx, DWORD PTR _BitCount
	add	ecx, DWORD PTR _i$12[ebp]
	shl	ecx, 1
	mov	DWORD PTR _src$4[ebp], ecx
; Line 569
	mov	eax, DWORD PTR _curY$14[ebp]
	imul	ecx, DWORD PTR [eax], 80
	add	ecx, DWORD PTR _minX$8[ebp]
	add	ecx, DWORD PTR _i$12[ebp]
	shl	ecx, 1
	mov	DWORD PTR _dst$2[ebp], ecx
; Line 570
	mov	edx, DWORD PTR _VgaMemoryAddress
	add	edx, DWORD PTR _dst$2[ebp]
	mov	eax, DWORD PTR _VgaMemoryAddress
	add	eax, DWORD PTR _src$4[ebp]
	mov	cl, BYTE PTR [eax]
	mov	BYTE PTR [edx], cl
; Line 571
	mov	edx, DWORD PTR _VgaMemoryAddress
	add	edx, DWORD PTR _src$4[ebp]
	mov	BYTE PTR [edx], 32			; 00000020H
; Line 572
	jmp	SHORT $LN2@KeyboardDr
$LN3@KeyboardDr:
; Line 573
	mov	eax, DWORD PTR _minX$8[ebp]
	add	eax, DWORD PTR _BitCount
	mov	ecx, DWORD PTR _curX$11[ebp]
	mov	DWORD PTR [ecx], eax
$LN25@KeyboardDr:
; Line 576
	mov	edx, DWORD PTR _OvertypeMode
	push	edx
	mov	eax, DWORD PTR _maxX$6[ebp]
	push	eax
	mov	ecx, DWORD PTR _minX$8[ebp]
	push	ecx
	mov	edx, DWORD PTR _curY$14[ebp]
	push	edx
	mov	eax, DWORD PTR _curX$11[ebp]
	push	eax
	push	49					; 00000031H
	call	_TypeChar
	add	esp, 24					; 00000018H
; Line 577
	mov	ecx, DWORD PTR _BitCount
	add	ecx, 1
	mov	DWORD PTR _BitCount, ecx
; Line 578
	cmp	DWORD PTR _BitCount, 8
	jne	SHORT $LN27@KeyboardDr
; Line 579
	mov	edx, DWORD PTR _OvertypeMode
	push	edx
	mov	eax, DWORD PTR _maxX$6[ebp]
	push	eax
	mov	ecx, DWORD PTR _minX$8[ebp]
	push	ecx
	mov	edx, DWORD PTR _curY$14[ebp]
	push	edx
	mov	eax, DWORD PTR _curX$11[ebp]
	push	eax
	push	32					; 00000020H
	call	_TypeChar
	add	esp, 24					; 00000018H
; Line 580
	mov	DWORD PTR _BitCount, 0
$LN27@KeyboardDr:
; Line 582
	jmp	$LN32@KeyboardDr
$LN17@KeyboardDr:
; Line 583
	movzx	ecx, BYTE PTR _Scancode$15[ebp]
	cmp	ecx, 11					; 0000000bH
	jne	$LN32@KeyboardDr
; Line 584
	cmp	DWORD PTR _InsertHeld, 0
	jne	$LN32@KeyboardDr
	cmp	DWORD PTR _NothingToSeeHere, 1
	jne	$LN32@KeyboardDr
; Line 585
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN51@KeyboardDr
	mov	DWORD PTR tv181[ebp], OFFSET _RightX
	jmp	SHORT $LN52@KeyboardDr
$LN51@KeyboardDr:
	mov	DWORD PTR tv181[ebp], OFFSET _LeftX
$LN52@KeyboardDr:
	mov	edx, DWORD PTR tv181[ebp]
	mov	DWORD PTR _curX$9[ebp], edx
; Line 586
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN53@KeyboardDr
	mov	DWORD PTR tv183[ebp], OFFSET _RightY
	jmp	SHORT $LN54@KeyboardDr
$LN53@KeyboardDr:
	mov	DWORD PTR tv183[ebp], OFFSET _LeftY
$LN54@KeyboardDr:
	mov	eax, DWORD PTR tv183[ebp]
	mov	DWORD PTR _curY$13[ebp], eax
; Line 587
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN55@KeyboardDr
	mov	DWORD PTR tv185[ebp], 54		; 00000036H
	jmp	SHORT $LN56@KeyboardDr
$LN55@KeyboardDr:
	mov	DWORD PTR tv185[ebp], 4
$LN56@KeyboardDr:
	mov	ecx, DWORD PTR tv185[ebp]
	mov	DWORD PTR _minX$7[ebp], ecx
; Line 588
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN57@KeyboardDr
	mov	DWORD PTR tv187[ebp], 79		; 0000004fH
	jmp	SHORT $LN58@KeyboardDr
$LN57@KeyboardDr:
	mov	DWORD PTR tv187[ebp], 49		; 00000031H
$LN58@KeyboardDr:
	mov	edx, DWORD PTR tv187[ebp]
	mov	DWORD PTR _maxX$5[ebp], edx
; Line 590
	mov	eax, DWORD PTR _curX$9[ebp]
	mov	ecx, DWORD PTR [eax]
	add	ecx, 8
	sub	ecx, DWORD PTR _BitCount
	cmp	ecx, DWORD PTR _maxX$5[ebp]
	jl	$LN30@KeyboardDr
; Line 591
	mov	edx, DWORD PTR _curY$13[ebp]
	mov	eax, DWORD PTR [edx]
	add	eax, 1
	mov	ecx, DWORD PTR _curY$13[ebp]
	mov	DWORD PTR [ecx], eax
; Line 592
	cmp	DWORD PTR _curY$13[ebp], OFFSET _LeftY
	jne	SHORT $LN31@KeyboardDr
	call	_ScrollCed
	npad	1
$LN31@KeyboardDr:
; Line 594
	mov	DWORD PTR _i$10[ebp], 0
	jmp	SHORT $LN7@KeyboardDr
$LN5@KeyboardDr:
	mov	edx, DWORD PTR _i$10[ebp]
	add	edx, 1
	mov	DWORD PTR _i$10[ebp], edx
$LN7@KeyboardDr:
	mov	eax, DWORD PTR _i$10[ebp]
	cmp	eax, DWORD PTR _BitCount
	jge	SHORT $LN6@KeyboardDr
; Line 595
	mov	ecx, DWORD PTR _curY$13[ebp]
	mov	edx, DWORD PTR [ecx]
	sub	edx, 1
	imul	eax, edx, 80
	mov	ecx, DWORD PTR _curX$9[ebp]
	add	eax, DWORD PTR [ecx]
	sub	eax, DWORD PTR _BitCount
	add	eax, DWORD PTR _i$10[ebp]
	shl	eax, 1
	mov	DWORD PTR _src$3[ebp], eax
; Line 596
	mov	edx, DWORD PTR _curY$13[ebp]
	imul	eax, DWORD PTR [edx], 80
	add	eax, DWORD PTR _minX$7[ebp]
	add	eax, DWORD PTR _i$10[ebp]
	shl	eax, 1
	mov	DWORD PTR _dst$1[ebp], eax
; Line 597
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _dst$1[ebp]
	mov	edx, DWORD PTR _VgaMemoryAddress
	add	edx, DWORD PTR _src$3[ebp]
	mov	al, BYTE PTR [edx]
	mov	BYTE PTR [ecx], al
; Line 598
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _src$3[ebp]
	mov	BYTE PTR [ecx], 32			; 00000020H
; Line 599
	jmp	SHORT $LN5@KeyboardDr
$LN6@KeyboardDr:
; Line 600
	mov	edx, DWORD PTR _minX$7[ebp]
	add	edx, DWORD PTR _BitCount
	mov	eax, DWORD PTR _curX$9[ebp]
	mov	DWORD PTR [eax], edx
$LN30@KeyboardDr:
; Line 603
	mov	ecx, DWORD PTR _OvertypeMode
	push	ecx
	mov	edx, DWORD PTR _maxX$5[ebp]
	push	edx
	mov	eax, DWORD PTR _minX$7[ebp]
	push	eax
	mov	ecx, DWORD PTR _curY$13[ebp]
	push	ecx
	mov	edx, DWORD PTR _curX$9[ebp]
	push	edx
	push	48					; 00000030H
	call	_TypeChar
	add	esp, 24					; 00000018H
; Line 604
	mov	eax, DWORD PTR _BitCount
	add	eax, 1
	mov	DWORD PTR _BitCount, eax
; Line 605
	cmp	DWORD PTR _BitCount, 8
	jne	SHORT $LN32@KeyboardDr
; Line 606
	mov	ecx, DWORD PTR _OvertypeMode
	push	ecx
	mov	edx, DWORD PTR _maxX$5[ebp]
	push	edx
	mov	eax, DWORD PTR _minX$7[ebp]
	push	eax
	mov	ecx, DWORD PTR _curY$13[ebp]
	push	ecx
	mov	edx, DWORD PTR _curX$9[ebp]
	push	edx
	push	32					; 00000020H
	call	_TypeChar
	add	esp, 24					; 00000018H
; Line 607
	mov	DWORD PTR _BitCount, 0
$LN32@KeyboardDr:
; Line 612
	cmp	DWORD PTR _ActiveBox, 0
	jne	SHORT $LN33@KeyboardDr
	cmp	DWORD PTR _NothingToSeeHere, 1
	jne	SHORT $LN33@KeyboardDr
	mov	eax, DWORD PTR _RightY
	push	eax
	mov	ecx, DWORD PTR _RightX
	push	ecx
	call	_UnderscoreCursorGoesHereAt
	add	esp, 8
	jmp	SHORT $LN34@KeyboardDr
$LN33@KeyboardDr:
; Line 613
	mov	edx, DWORD PTR _LeftY
	push	edx
	mov	eax, DWORD PTR _LeftX
	push	eax
	call	_UnderscoreCursorGoesHereAt
	add	esp, 8
$LN34@KeyboardDr:
; Line 616
	cmp	DWORD PTR _InsertTimer, 0
	jle	SHORT $LN35@KeyboardDr
	mov	ecx, DWORD PTR _InsertTimer
	sub	ecx, 1
	mov	DWORD PTR _InsertTimer, ecx
$LN35@KeyboardDr:
; Line 617
	mov	esp, ebp
	pop	ebp
	ret	0
_KeyboardDriver ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_end_index$1 = -12					; size = 4
_index$ = -8						; size = 4
_i$2 = -4						; size = 4
_c$ = 8							; size = 1
_x$ = 12						; size = 4
_y$ = 16						; size = 4
_minX$ = 20						; size = 4
_maxX$ = 24						; size = 4
_overtype$ = 28						; size = 4
_TypeChar PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 502
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 503
	mov	eax, DWORD PTR _y$[ebp]
	imul	ecx, DWORD PTR [eax], 80
	mov	edx, DWORD PTR _x$[ebp]
	add	ecx, DWORD PTR [edx]
	shl	ecx, 1
	mov	DWORD PTR _index$[ebp], ecx
; Line 504
	cmp	DWORD PTR _overtype$[ebp], 0
	jne	SHORT $LN3@TypeChar
; Line 505
	mov	eax, DWORD PTR _y$[ebp]
	imul	ecx, DWORD PTR [eax], 80
	mov	edx, DWORD PTR _maxX$[ebp]
	lea	eax, DWORD PTR [ecx+edx-1]
	shl	eax, 1
	mov	DWORD PTR _end_index$1[ebp], eax
; Line 506
	mov	ecx, DWORD PTR _end_index$1[ebp]
	mov	DWORD PTR _i$2[ebp], ecx
	jmp	SHORT $LN4@TypeChar
$LN2@TypeChar:
	mov	edx, DWORD PTR _i$2[ebp]
	sub	edx, 2
	mov	DWORD PTR _i$2[ebp], edx
$LN4@TypeChar:
	mov	eax, DWORD PTR _i$2[ebp]
	cmp	eax, DWORD PTR _index$[ebp]
	jle	SHORT $LN3@TypeChar
; Line 507
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _VgaMemoryAddress
	add	edx, DWORD PTR _i$2[ebp]
	mov	al, BYTE PTR [edx-2]
	mov	BYTE PTR [ecx], al
; Line 508
	jmp	SHORT $LN2@TypeChar
$LN3@TypeChar:
; Line 510
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _index$[ebp]
	mov	dl, BYTE PTR _c$[ebp]
	mov	BYTE PTR [ecx], dl
; Line 511
	mov	eax, DWORD PTR _VgaMemoryAddress
	add	eax, DWORD PTR _index$[ebp]
	mov	BYTE PTR [eax+1], 7
; Line 512
	mov	ecx, DWORD PTR _x$[ebp]
	mov	edx, DWORD PTR [ecx]
	add	edx, 1
	mov	eax, DWORD PTR _x$[ebp]
	mov	DWORD PTR [eax], edx
; Line 513
	mov	ecx, DWORD PTR _x$[ebp]
	mov	edx, DWORD PTR [ecx]
	cmp	edx, DWORD PTR _maxX$[ebp]
	jl	SHORT $LN7@TypeChar
; Line 514
	mov	eax, DWORD PTR _x$[ebp]
	mov	ecx, DWORD PTR _minX$[ebp]
	mov	DWORD PTR [eax], ecx
; Line 515
	mov	edx, DWORD PTR _y$[ebp]
	mov	eax, DWORD PTR [edx]
	add	eax, 1
	mov	ecx, DWORD PTR _y$[ebp]
	mov	DWORD PTR [ecx], eax
; Line 516
	cmp	DWORD PTR _y$[ebp], OFFSET _LeftY
	jne	SHORT $LN7@TypeChar
	cmp	DWORD PTR _NothingToSeeHere, 1
	jne	SHORT $LN7@TypeChar
	call	_ScrollCed
	npad	1
$LN7@TypeChar:
; Line 518
	mov	esp, ebp
	pop	ebp
	ret	0
_TypeChar ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_cmd$ = -244						; size = 128
_func$1 = -116						; size = 4
_codeBuf$2 = -112					; size = 4
_idx$3 = -108						; size = 4
_vgaIdx$4 = -104					; size = 4
_endCol$5 = -100					; size = 4
_startCol$6 = -96					; size = 4
_idx$7 = -92						; size = 4
_idx$8 = -88						; size = 4
tv69 = -84						; size = 4
tv67 = -80						; size = 4
_codeIdx$9 = -76					; size = 4
_bBits$10 = -72						; size = 4
_bVal$11 = -68						; size = 4
_c$12 = -64						; size = 4
_r$13 = -60						; size = 4
_c$14 = -56						; size = 4
_r$15 = -52						; size = 4
_c$16 = -48						; size = 4
_r$17 = -44						; size = 4
_bitIndex$ = -40					; size = 4
_currentByte$ = -36					; size = 4
_col$18 = -32						; size = 4
_colNum$19 = -28					; size = 4
_idx$20 = -24						; size = 4
_rowNum$21 = -20					; size = 4
_idx$22 = -16						; size = 4
_cmdLen$ = -12						; size = 4
_r$23 = -8						; size = 4
_ch$24 = -2						; size = 1
_ch$25 = -1						; size = 1
_ExecuteNavCommand PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 420
	push	ebp
	mov	ebp, esp
	sub	esp, 244				; 000000f4H
; Line 422
	mov	DWORD PTR _cmdLen$[ebp], 0
	mov	DWORD PTR _currentByte$[ebp], 0
	mov	DWORD PTR _bitIndex$[ebp], 0
; Line 424
	mov	eax, DWORD PTR _NavCmdStartY
	mov	DWORD PTR _r$23[ebp], eax
	jmp	SHORT $LN4@ExecuteNav
$LN2@ExecuteNav:
	mov	ecx, DWORD PTR _r$23[ebp]
	add	ecx, 1
	mov	DWORD PTR _r$23[ebp], ecx
$LN4@ExecuteNav:
	mov	edx, DWORD PTR _r$23[ebp]
	cmp	edx, DWORD PTR _RightY
	jg	$LN3@ExecuteNav
; Line 425
	mov	eax, DWORD PTR _r$23[ebp]
	cmp	eax, DWORD PTR _NavCmdStartY
	jne	SHORT $LN50@ExecuteNav
	mov	ecx, DWORD PTR _NavCmdStartX
	mov	DWORD PTR tv67[ebp], ecx
	jmp	SHORT $LN51@ExecuteNav
$LN50@ExecuteNav:
	mov	DWORD PTR tv67[ebp], 54			; 00000036H
$LN51@ExecuteNav:
	mov	edx, DWORD PTR tv67[ebp]
	mov	DWORD PTR _startCol$6[ebp], edx
; Line 426
	mov	eax, DWORD PTR _r$23[ebp]
	cmp	eax, DWORD PTR _RightY
	jne	SHORT $LN52@ExecuteNav
	mov	ecx, DWORD PTR _RightX
	mov	DWORD PTR tv69[ebp], ecx
	jmp	SHORT $LN53@ExecuteNav
$LN52@ExecuteNav:
	mov	DWORD PTR tv69[ebp], 79			; 0000004fH
$LN53@ExecuteNav:
	mov	edx, DWORD PTR tv69[ebp]
	mov	DWORD PTR _endCol$5[ebp], edx
; Line 427
	mov	eax, DWORD PTR _startCol$6[ebp]
	mov	DWORD PTR _col$18[ebp], eax
	jmp	SHORT $LN7@ExecuteNav
$LN5@ExecuteNav:
	mov	ecx, DWORD PTR _col$18[ebp]
	add	ecx, 1
	mov	DWORD PTR _col$18[ebp], ecx
$LN7@ExecuteNav:
	mov	edx, DWORD PTR _col$18[ebp]
	cmp	edx, DWORD PTR _endCol$5[ebp]
	jge	SHORT $LN6@ExecuteNav
; Line 428
	imul	eax, DWORD PTR _r$23[ebp], 80
	add	eax, DWORD PTR _col$18[ebp]
	shl	eax, 1
	mov	DWORD PTR _vgaIdx$4[ebp], eax
; Line 429
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _vgaIdx$4[ebp]
	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR _ch$25[ebp], dl
; Line 430
	movsx	eax, BYTE PTR _ch$25[ebp]
	cmp	eax, 48					; 00000030H
	je	SHORT $LN31@ExecuteNav
	movsx	ecx, BYTE PTR _ch$25[ebp]
	cmp	ecx, 49					; 00000031H
	jne	SHORT $LN32@ExecuteNav
$LN31@ExecuteNav:
; Line 431
	mov	edx, DWORD PTR _currentByte$[ebp]
	shl	edx, 1
	movsx	eax, BYTE PTR _ch$25[ebp]
	sub	eax, 48					; 00000030H
	or	edx, eax
	mov	DWORD PTR _currentByte$[ebp], edx
; Line 432
	mov	ecx, DWORD PTR _bitIndex$[ebp]
	add	ecx, 1
	mov	DWORD PTR _bitIndex$[ebp], ecx
; Line 433
	cmp	DWORD PTR _bitIndex$[ebp], 8
	jne	SHORT $LN32@ExecuteNav
; Line 434
	cmp	DWORD PTR _cmdLen$[ebp], 127		; 0000007fH
	jge	SHORT $LN33@ExecuteNav
	mov	edx, DWORD PTR _cmdLen$[ebp]
	mov	al, BYTE PTR _currentByte$[ebp]
	mov	BYTE PTR _cmd$[ebp+edx], al
	mov	ecx, DWORD PTR _cmdLen$[ebp]
	add	ecx, 1
	mov	DWORD PTR _cmdLen$[ebp], ecx
$LN33@ExecuteNav:
; Line 435
	mov	DWORD PTR _currentByte$[ebp], 0
; Line 436
	mov	DWORD PTR _bitIndex$[ebp], 0
$LN32@ExecuteNav:
; Line 439
	jmp	$LN5@ExecuteNav
$LN6@ExecuteNav:
; Line 440
	jmp	$LN2@ExecuteNav
$LN3@ExecuteNav:
; Line 441
	mov	edx, DWORD PTR _cmdLen$[ebp]
	mov	BYTE PTR _cmd$[ebp+edx], 0
; Line 443
	push	OFFSET $SG30725
	lea	eax, DWORD PTR _cmd$[ebp]
	push	eax
	call	_IsSubstringMatch
	add	esp, 8
	test	eax, eax
	je	$LN34@ExecuteNav
; Line 444
	mov	DWORD PTR _r$17[ebp], 7
	jmp	SHORT $LN10@ExecuteNav
$LN8@ExecuteNav:
	mov	ecx, DWORD PTR _r$17[ebp]
	add	ecx, 1
	mov	DWORD PTR _r$17[ebp], ecx
$LN10@ExecuteNav:
	cmp	DWORD PTR _r$17[ebp], 22		; 00000016H
	jg	SHORT $LN9@ExecuteNav
; Line 445
	mov	DWORD PTR _c$16[ebp], 4
	jmp	SHORT $LN13@ExecuteNav
$LN11@ExecuteNav:
	mov	edx, DWORD PTR _c$16[ebp]
	add	edx, 1
	mov	DWORD PTR _c$16[ebp], edx
$LN13@ExecuteNav:
	cmp	DWORD PTR _c$16[ebp], 48		; 00000030H
	jg	SHORT $LN12@ExecuteNav
; Line 446
	imul	eax, DWORD PTR _r$17[ebp], 80
	add	eax, DWORD PTR _c$16[ebp]
	shl	eax, 1
	mov	DWORD PTR _idx$8[ebp], eax
; Line 447
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _idx$8[ebp]
	mov	BYTE PTR [ecx], 32			; 00000020H
; Line 448
	mov	edx, DWORD PTR _VgaMemoryAddress
	add	edx, DWORD PTR _idx$8[ebp]
	mov	BYTE PTR [edx+1], 7
; Line 449
	jmp	SHORT $LN11@ExecuteNav
$LN12@ExecuteNav:
; Line 450
	jmp	SHORT $LN8@ExecuteNav
$LN9@ExecuteNav:
; Line 451
	mov	DWORD PTR _LeftX, 4
	mov	DWORD PTR _LeftY, 7
	mov	DWORD PTR _CedBaseLine, 1
; Line 452
	call	_RedrawCedLineNumbers
	npad	1
	jmp	$LN48@ExecuteNav
$LN34@ExecuteNav:
; Line 453
	push	OFFSET $SG30728
	lea	eax, DWORD PTR _cmd$[ebp]
	push	eax
	call	_IsSubstringMatch
	add	esp, 8
	test	eax, eax
	je	SHORT $LN36@ExecuteNav
; Line 454
	mov	DWORD PTR _r$15[ebp], 7
	jmp	SHORT $LN16@ExecuteNav
$LN14@ExecuteNav:
	mov	ecx, DWORD PTR _r$15[ebp]
	add	ecx, 1
	mov	DWORD PTR _r$15[ebp], ecx
$LN16@ExecuteNav:
	cmp	DWORD PTR _r$15[ebp], 22		; 00000016H
	jg	SHORT $LN15@ExecuteNav
; Line 455
	mov	DWORD PTR _c$14[ebp], 54		; 00000036H
	jmp	SHORT $LN19@ExecuteNav
$LN17@ExecuteNav:
	mov	edx, DWORD PTR _c$14[ebp]
	add	edx, 1
	mov	DWORD PTR _c$14[ebp], edx
$LN19@ExecuteNav:
	cmp	DWORD PTR _c$14[ebp], 78		; 0000004eH
	jg	SHORT $LN18@ExecuteNav
; Line 456
	imul	eax, DWORD PTR _r$15[ebp], 80
	add	eax, DWORD PTR _c$14[ebp]
	shl	eax, 1
	mov	DWORD PTR _idx$7[ebp], eax
; Line 457
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _idx$7[ebp]
	mov	BYTE PTR [ecx], 32			; 00000020H
; Line 458
	mov	edx, DWORD PTR _VgaMemoryAddress
	add	edx, DWORD PTR _idx$7[ebp]
	mov	BYTE PTR [edx+1], 7
; Line 459
	jmp	SHORT $LN17@ExecuteNav
$LN18@ExecuteNav:
; Line 460
	jmp	SHORT $LN14@ExecuteNav
$LN15@ExecuteNav:
; Line 461
	mov	DWORD PTR _RightX, 54			; 00000036H
	mov	DWORD PTR _RightY, 7
	jmp	$LN48@ExecuteNav
$LN36@ExecuteNav:
; Line 462
	push	OFFSET $SG30731
	lea	eax, DWORD PTR _cmd$[ebp]
	push	eax
	call	_IsSubstringMatch
	add	esp, 8
	test	eax, eax
	je	$LN38@ExecuteNav
; Line 463
	mov	DWORD PTR _codeBuf$2[ebp], 524288	; 00080000H
; Line 464
	mov	DWORD PTR _codeIdx$9[ebp], 0
; Line 465
	mov	DWORD PTR _r$13[ebp], 7
	jmp	SHORT $LN22@ExecuteNav
$LN20@ExecuteNav:
	mov	ecx, DWORD PTR _r$13[ebp]
	add	ecx, 1
	mov	DWORD PTR _r$13[ebp], ecx
$LN22@ExecuteNav:
	cmp	DWORD PTR _r$13[ebp], 22		; 00000016H
	jg	$LN21@ExecuteNav
; Line 466
	mov	DWORD PTR _bVal$11[ebp], 0
	mov	DWORD PTR _bBits$10[ebp], 0
; Line 467
	mov	DWORD PTR _c$12[ebp], 4
	jmp	SHORT $LN25@ExecuteNav
$LN23@ExecuteNav:
	mov	edx, DWORD PTR _c$12[ebp]
	add	edx, 1
	mov	DWORD PTR _c$12[ebp], edx
$LN25@ExecuteNav:
	cmp	DWORD PTR _c$12[ebp], 48		; 00000030H
	jg	SHORT $LN24@ExecuteNav
; Line 468
	imul	eax, DWORD PTR _r$13[ebp], 80
	add	eax, DWORD PTR _c$12[ebp]
	shl	eax, 1
	mov	DWORD PTR _idx$3[ebp], eax
; Line 469
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _idx$3[ebp]
	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR _ch$24[ebp], dl
; Line 470
	movsx	eax, BYTE PTR _ch$24[ebp]
	cmp	eax, 48					; 00000030H
	je	SHORT $LN41@ExecuteNav
	movsx	ecx, BYTE PTR _ch$24[ebp]
	cmp	ecx, 49					; 00000031H
	jne	SHORT $LN42@ExecuteNav
$LN41@ExecuteNav:
; Line 471
	mov	edx, DWORD PTR _bVal$11[ebp]
	shl	edx, 1
	movsx	eax, BYTE PTR _ch$24[ebp]
	sub	eax, 48					; 00000030H
	or	edx, eax
	mov	DWORD PTR _bVal$11[ebp], edx
; Line 472
	mov	ecx, DWORD PTR _bBits$10[ebp]
	add	ecx, 1
	mov	DWORD PTR _bBits$10[ebp], ecx
; Line 473
	cmp	DWORD PTR _bBits$10[ebp], 8
	jne	SHORT $LN42@ExecuteNav
; Line 474
	mov	edx, DWORD PTR _codeBuf$2[ebp]
	add	edx, DWORD PTR _codeIdx$9[ebp]
	mov	al, BYTE PTR _bVal$11[ebp]
	mov	BYTE PTR [edx], al
	mov	ecx, DWORD PTR _codeIdx$9[ebp]
	add	ecx, 1
	mov	DWORD PTR _codeIdx$9[ebp], ecx
; Line 475
	mov	DWORD PTR _bVal$11[ebp], 0
	mov	DWORD PTR _bBits$10[ebp], 0
$LN42@ExecuteNav:
; Line 478
	jmp	SHORT $LN23@ExecuteNav
$LN24@ExecuteNav:
; Line 479
	jmp	$LN20@ExecuteNav
$LN21@ExecuteNav:
; Line 480
	cmp	DWORD PTR _codeIdx$9[ebp], 0
	jle	SHORT $LN43@ExecuteNav
; Line 481
	mov	DWORD PTR _func$1[ebp], 524288		; 00080000H
; Line 482
	call	DWORD PTR _func$1[ebp]
	npad	1
$LN43@ExecuteNav:
; Line 483
	jmp	$LN48@ExecuteNav
$LN38@ExecuteNav:
; Line 484
	push	OFFSET $SG30738
	lea	edx, DWORD PTR _cmd$[ebp]
	push	edx
	call	_IsSubstringMatch
	add	esp, 8
	test	eax, eax
	je	SHORT $LN44@ExecuteNav
; Line 485
	mov	DWORD PTR _rowNum$21[ebp], 0
	mov	DWORD PTR _idx$22[ebp], 13		; 0000000dH
$LN26@ExecuteNav:
; Line 486
	mov	eax, DWORD PTR _idx$22[ebp]
	movsx	ecx, BYTE PTR _cmd$[ebp+eax]
	cmp	ecx, 48					; 00000030H
	jl	SHORT $LN27@ExecuteNav
	mov	edx, DWORD PTR _idx$22[ebp]
	movsx	eax, BYTE PTR _cmd$[ebp+edx]
	cmp	eax, 57					; 00000039H
	jg	SHORT $LN27@ExecuteNav
; Line 487
	imul	ecx, DWORD PTR _rowNum$21[ebp], 10
	mov	edx, DWORD PTR _idx$22[ebp]
	movsx	eax, BYTE PTR _cmd$[ebp+edx]
	lea	ecx, DWORD PTR [ecx+eax-48]
	mov	DWORD PTR _rowNum$21[ebp], ecx
	mov	edx, DWORD PTR _idx$22[ebp]
	add	edx, 1
	mov	DWORD PTR _idx$22[ebp], edx
; Line 488
	jmp	SHORT $LN26@ExecuteNav
$LN27@ExecuteNav:
; Line 489
	cmp	DWORD PTR _rowNum$21[ebp], 1
	jl	SHORT $LN46@ExecuteNav
	cmp	DWORD PTR _rowNum$21[ebp], 16		; 00000010H
	jg	SHORT $LN46@ExecuteNav
	mov	eax, DWORD PTR _rowNum$21[ebp]
	add	eax, 6
	mov	DWORD PTR _LeftY, eax
$LN46@ExecuteNav:
; Line 490
	jmp	SHORT $LN48@ExecuteNav
$LN44@ExecuteNav:
	push	OFFSET $SG30741
	lea	ecx, DWORD PTR _cmd$[ebp]
	push	ecx
	call	_IsSubstringMatch
	add	esp, 8
	test	eax, eax
	je	SHORT $LN48@ExecuteNav
; Line 491
	mov	DWORD PTR _colNum$19[ebp], 0
	mov	DWORD PTR _idx$20[ebp], 13		; 0000000dH
$LN28@ExecuteNav:
; Line 492
	mov	edx, DWORD PTR _idx$20[ebp]
	movsx	eax, BYTE PTR _cmd$[ebp+edx]
	cmp	eax, 48					; 00000030H
	jl	SHORT $LN29@ExecuteNav
	mov	ecx, DWORD PTR _idx$20[ebp]
	movsx	edx, BYTE PTR _cmd$[ebp+ecx]
	cmp	edx, 57					; 00000039H
	jg	SHORT $LN29@ExecuteNav
; Line 493
	imul	eax, DWORD PTR _colNum$19[ebp], 10
	mov	ecx, DWORD PTR _idx$20[ebp]
	movsx	edx, BYTE PTR _cmd$[ebp+ecx]
	lea	eax, DWORD PTR [eax+edx-48]
	mov	DWORD PTR _colNum$19[ebp], eax
	mov	ecx, DWORD PTR _idx$20[ebp]
	add	ecx, 1
	mov	DWORD PTR _idx$20[ebp], ecx
; Line 494
	jmp	SHORT $LN28@ExecuteNav
$LN29@ExecuteNav:
; Line 495
	cmp	DWORD PTR _colNum$19[ebp], 1
	jl	SHORT $LN48@ExecuteNav
	cmp	DWORD PTR _colNum$19[ebp], 25		; 00000019H
	jg	SHORT $LN48@ExecuteNav
	mov	edx, DWORD PTR _colNum$19[ebp]
	add	edx, 3
	mov	DWORD PTR _LeftX, edx
$LN48@ExecuteNav:
; Line 497
	mov	esp, ebp
	pop	ebp
	ret	0
_ExecuteNavCommand ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_idx$1 = -24						; size = 4
_src$2 = -20						; size = 4
_dst$3 = -16						; size = 4
_c$4 = -12						; size = 4
_c$5 = -8						; size = 4
_r$6 = -4						; size = 4
_ScrollCed PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 394
	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
; Line 395
	cmp	DWORD PTR _LeftY, 22			; 00000016H
	jle	$LN11@ScrollCed
; Line 396
	mov	DWORD PTR _r$6[ebp], 7
	jmp	SHORT $LN4@ScrollCed
$LN2@ScrollCed:
	mov	eax, DWORD PTR _r$6[ebp]
	add	eax, 1
	mov	DWORD PTR _r$6[ebp], eax
$LN4@ScrollCed:
	cmp	DWORD PTR _r$6[ebp], 22			; 00000016H
	jge	SHORT $LN3@ScrollCed
; Line 397
	mov	DWORD PTR _c$5[ebp], 4
	jmp	SHORT $LN7@ScrollCed
$LN5@ScrollCed:
	mov	ecx, DWORD PTR _c$5[ebp]
	add	ecx, 1
	mov	DWORD PTR _c$5[ebp], ecx
$LN7@ScrollCed:
	cmp	DWORD PTR _c$5[ebp], 48			; 00000030H
	jg	SHORT $LN6@ScrollCed
; Line 398
	imul	edx, DWORD PTR _r$6[ebp], 80
	add	edx, DWORD PTR _c$5[ebp]
	shl	edx, 1
	mov	DWORD PTR _dst$3[ebp], edx
; Line 399
	mov	eax, DWORD PTR _r$6[ebp]
	add	eax, 1
	imul	ecx, eax, 80
	add	ecx, DWORD PTR _c$5[ebp]
	shl	ecx, 1
	mov	DWORD PTR _src$2[ebp], ecx
; Line 400
	mov	edx, DWORD PTR _VgaMemoryAddress
	add	edx, DWORD PTR _dst$3[ebp]
	mov	eax, DWORD PTR _VgaMemoryAddress
	add	eax, DWORD PTR _src$2[ebp]
	mov	cl, BYTE PTR [eax]
	mov	BYTE PTR [edx], cl
; Line 401
	mov	edx, DWORD PTR _VgaMemoryAddress
	add	edx, DWORD PTR _dst$3[ebp]
	mov	eax, DWORD PTR _VgaMemoryAddress
	add	eax, DWORD PTR _src$2[ebp]
	mov	cl, BYTE PTR [eax+1]
	mov	BYTE PTR [edx+1], cl
; Line 402
	jmp	SHORT $LN5@ScrollCed
$LN6@ScrollCed:
; Line 403
	jmp	SHORT $LN2@ScrollCed
$LN3@ScrollCed:
; Line 404
	mov	DWORD PTR _c$4[ebp], 4
	jmp	SHORT $LN10@ScrollCed
$LN8@ScrollCed:
	mov	edx, DWORD PTR _c$4[ebp]
	add	edx, 1
	mov	DWORD PTR _c$4[ebp], edx
$LN10@ScrollCed:
	cmp	DWORD PTR _c$4[ebp], 48			; 00000030H
	jg	SHORT $LN9@ScrollCed
; Line 405
	mov	eax, DWORD PTR _c$4[ebp]
	lea	ecx, DWORD PTR [eax+eax+3520]
	mov	DWORD PTR _idx$1[ebp], ecx
; Line 406
	mov	edx, DWORD PTR _VgaMemoryAddress
	add	edx, DWORD PTR _idx$1[ebp]
	mov	BYTE PTR [edx], 32			; 00000020H
; Line 407
	mov	eax, DWORD PTR _VgaMemoryAddress
	add	eax, DWORD PTR _idx$1[ebp]
	mov	BYTE PTR [eax+1], 7
; Line 408
	jmp	SHORT $LN8@ScrollCed
$LN9@ScrollCed:
; Line 409
	mov	ecx, DWORD PTR _CedBaseLine
	add	ecx, 1
	mov	DWORD PTR _CedBaseLine, ecx
; Line 410
	call	_RedrawCedLineNumbers
; Line 411
	mov	DWORD PTR _LeftY, 22			; 00000016H
$LN11@ScrollCed:
; Line 413
	mov	esp, ebp
	pop	ebp
	ret	0
_ScrollCed ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_i$1 = -4						; size = 4
_RedrawCedLineNumbers PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 387
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 388
	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN4@RedrawCedL
$LN2@RedrawCedL:
	mov	eax, DWORD PTR _i$1[ebp]
	add	eax, 1
	mov	DWORD PTR _i$1[ebp], eax
$LN4@RedrawCedL:
	cmp	DWORD PTR _i$1[ebp], 16			; 00000010H
	jge	SHORT $LN3@RedrawCedL
; Line 389
	mov	ecx, DWORD PTR _i$1[ebp]
	add	ecx, 7
	push	ecx
	push	1
	call	_SetCursorPosition
	add	esp, 8
; Line 390
	mov	edx, DWORD PTR _CedBaseLine
	add	edx, DWORD PTR _i$1[ebp]
	push	edx
	call	_kprint_int
	add	esp, 4
; Line 391
	jmp	SHORT $LN2@RedrawCedL
$LN3@RedrawCedL:
; Line 392
	mov	esp, ebp
	pop	ebp
	ret	0
_RedrawCedLineNumbers ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Position$ = -4						; size = 2
_ColumnX$ = 8						; size = 4
_RowY$ = 12						; size = 4
_UnderscoreCursorGoesHereAt PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 376
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 377
	imul	eax, DWORD PTR _RowY$[ebp], 80
	add	eax, DWORD PTR _ColumnX$[ebp]
	shl	eax, 1
	mov	DWORD PTR _VgaBufferIndex, eax
; Line 379
	imul	ecx, DWORD PTR _RowY$[ebp], 80
	add	ecx, DWORD PTR _ColumnX$[ebp]
	mov	WORD PTR _Position$[ebp], cx
; Line 380
	mov	edx, 980				; 000003d4H
	mov	al, 15					; 0000000fH
	out	dx, al
; Line 381
	movzx	eax, WORD PTR _Position$[ebp]
	and	eax, 255				; 000000ffH
	mov	edx, 981				; 000003d5H
	out	dx, al
; Line 382
	mov	edx, 980				; 000003d4H
	mov	al, 14					; 0000000eH
	out	dx, al
; Line 383
	movzx	eax, WORD PTR _Position$[ebp]
	sar	eax, 8
	and	eax, 255				; 000000ffH
	mov	edx, 981				; 000003d5H
	out	dx, al
; Line 384
	mov	esp, ebp
	pop	ebp
	ret	0
_UnderscoreCursorGoesHereAt ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Index$1 = -8						; size = 4
_i$2 = -4						; size = 4
_DrawLayout PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 352
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 353
	mov	DWORD PTR _VgaBufferIndex, 0
; Line 354
	mov	DWORD PTR _Index$1[ebp], 0
	jmp	SHORT $LN4@DrawLayout
$LN2@DrawLayout:
	mov	eax, DWORD PTR _Index$1[ebp]
	add	eax, 1
	mov	DWORD PTR _Index$1[ebp], eax
$LN4@DrawLayout:
	cmp	DWORD PTR _Index$1[ebp], 2000		; 000007d0H
	jge	SHORT $LN3@DrawLayout
; Line 355
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _VgaBufferIndex
	mov	BYTE PTR [ecx], 32			; 00000020H
	mov	edx, DWORD PTR _VgaBufferIndex
	add	edx, 1
	mov	DWORD PTR _VgaBufferIndex, edx
; Line 356
	mov	eax, DWORD PTR _VgaMemoryAddress
	add	eax, DWORD PTR _VgaBufferIndex
	mov	BYTE PTR [eax], 7
	mov	ecx, DWORD PTR _VgaBufferIndex
	add	ecx, 1
	mov	DWORD PTR _VgaBufferIndex, ecx
; Line 357
	jmp	SHORT $LN2@DrawLayout
$LN3@DrawLayout:
; Line 359
	push	6
	push	80					; 00000050H
	push	0
	push	0
	call	_DrawLayoutBox
	add	esp, 16					; 00000010H
; Line 361
	push	19					; 00000013H
	push	50					; 00000032H
	push	6
	push	0
	call	_DrawLayoutBox
	add	esp, 16					; 00000010H
; Line 363
	push	19					; 00000013H
	push	30					; 0000001eH
	push	6
	push	50					; 00000032H
	call	_DrawLayoutBox
	add	esp, 16					; 00000010H
; Line 366
	mov	DWORD PTR _i$2[ebp], 0
	jmp	SHORT $LN7@DrawLayout
$LN5@DrawLayout:
	mov	edx, DWORD PTR _i$2[ebp]
	add	edx, 1
	mov	DWORD PTR _i$2[ebp], edx
$LN7@DrawLayout:
	cmp	DWORD PTR _i$2[ebp], 16			; 00000010H
	jge	SHORT $LN6@DrawLayout
; Line 367
	mov	eax, DWORD PTR _i$2[ebp]
	add	eax, 7
	push	eax
	push	1
	call	_SetCursorPosition
	add	esp, 8
; Line 368
	mov	ecx, DWORD PTR _i$2[ebp]
	add	ecx, 1
	push	ecx
	call	_kprint_int
	add	esp, 4
; Line 369
	mov	edx, DWORD PTR _i$2[ebp]
	add	edx, 7
	push	edx
	push	51					; 00000033H
	call	_SetCursorPosition
	add	esp, 8
; Line 370
	mov	eax, DWORD PTR _i$2[ebp]
	add	eax, 1
	push	eax
	call	_kprint_int
	add	esp, 4
; Line 371
	jmp	SHORT $LN5@DrawLayout
$LN6@DrawLayout:
; Line 372
	mov	esp, ebp
	pop	ebp
	ret	0
_DrawLayout ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_HorizontalIndex$1 = -12				; size = 4
_HorizontalIndex$2 = -8					; size = 4
_VerticalIndex$3 = -4					; size = 4
_StartX$ = 8						; size = 4
_StartY$ = 12						; size = 4
_BoxWidth$ = 16						; size = 4
_BoxHeight$ = 20					; size = 4
_DrawLayoutBox PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 327
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 328
	mov	eax, DWORD PTR _StartY$[ebp]
	push	eax
	mov	ecx, DWORD PTR _StartX$[ebp]
	push	ecx
	call	_SetCursorPosition
	add	esp, 8
; Line 329
	push	43					; 0000002bH
	call	_KernelPrintCharacter
	add	esp, 4
; Line 330
	mov	DWORD PTR _HorizontalIndex$2[ebp], 1
	jmp	SHORT $LN4@DrawLayout
$LN2@DrawLayout:
	mov	edx, DWORD PTR _HorizontalIndex$2[ebp]
	add	edx, 1
	mov	DWORD PTR _HorizontalIndex$2[ebp], edx
$LN4@DrawLayout:
	mov	eax, DWORD PTR _BoxWidth$[ebp]
	sub	eax, 1
	cmp	DWORD PTR _HorizontalIndex$2[ebp], eax
	jge	SHORT $LN3@DrawLayout
; Line 331
	push	45					; 0000002dH
	call	_KernelPrintCharacter
	add	esp, 4
; Line 332
	jmp	SHORT $LN2@DrawLayout
$LN3@DrawLayout:
; Line 333
	push	43					; 0000002bH
	call	_KernelPrintCharacter
	add	esp, 4
; Line 335
	mov	ecx, DWORD PTR _StartY$[ebp]
	add	ecx, 1
	mov	DWORD PTR _VerticalIndex$3[ebp], ecx
	jmp	SHORT $LN7@DrawLayout
$LN5@DrawLayout:
	mov	edx, DWORD PTR _VerticalIndex$3[ebp]
	add	edx, 1
	mov	DWORD PTR _VerticalIndex$3[ebp], edx
$LN7@DrawLayout:
	mov	eax, DWORD PTR _BoxHeight$[ebp]
	mov	ecx, DWORD PTR _StartY$[ebp]
	lea	edx, DWORD PTR [ecx+eax-1]
	cmp	DWORD PTR _VerticalIndex$3[ebp], edx
	jge	SHORT $LN6@DrawLayout
; Line 336
	mov	eax, DWORD PTR _VerticalIndex$3[ebp]
	push	eax
	mov	ecx, DWORD PTR _StartX$[ebp]
	push	ecx
	call	_SetCursorPosition
	add	esp, 8
; Line 337
	push	124					; 0000007cH
	call	_KernelPrintCharacter
	add	esp, 4
; Line 338
	mov	edx, DWORD PTR _VerticalIndex$3[ebp]
	push	edx
	mov	eax, DWORD PTR _BoxWidth$[ebp]
	mov	ecx, DWORD PTR _StartX$[ebp]
	lea	edx, DWORD PTR [ecx+eax-1]
	push	edx
	call	_SetCursorPosition
	add	esp, 8
; Line 339
	push	124					; 0000007cH
	call	_KernelPrintCharacter
	add	esp, 4
; Line 340
	jmp	SHORT $LN5@DrawLayout
$LN6@DrawLayout:
; Line 342
	mov	eax, DWORD PTR _BoxHeight$[ebp]
	mov	ecx, DWORD PTR _StartY$[ebp]
	lea	edx, DWORD PTR [ecx+eax-1]
	push	edx
	mov	eax, DWORD PTR _StartX$[ebp]
	push	eax
	call	_SetCursorPosition
	add	esp, 8
; Line 343
	push	43					; 0000002bH
	call	_KernelPrintCharacter
	add	esp, 4
; Line 344
	mov	DWORD PTR _HorizontalIndex$1[ebp], 1
	jmp	SHORT $LN10@DrawLayout
$LN8@DrawLayout:
	mov	ecx, DWORD PTR _HorizontalIndex$1[ebp]
	add	ecx, 1
	mov	DWORD PTR _HorizontalIndex$1[ebp], ecx
$LN10@DrawLayout:
	mov	edx, DWORD PTR _BoxWidth$[ebp]
	sub	edx, 1
	cmp	DWORD PTR _HorizontalIndex$1[ebp], edx
	jge	SHORT $LN9@DrawLayout
; Line 345
	push	45					; 0000002dH
	call	_KernelPrintCharacter
	add	esp, 4
; Line 346
	jmp	SHORT $LN8@DrawLayout
$LN9@DrawLayout:
; Line 347
	push	43					; 0000002bH
	call	_KernelPrintCharacter
	add	esp, 4
; Line 348
	mov	esp, ebp
	pop	ebp
	ret	0
_DrawLayoutBox ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv70 = -4						; size = 4
_ColumnX$ = 8						; size = 4
_RowY$ = 12						; size = 4
_Color$ = 16						; size = 1
_SetCursorAndColor PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 322
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 323
	imul	eax, DWORD PTR _RowY$[ebp], 80
	add	eax, DWORD PTR _ColumnX$[ebp]
	shl	eax, 1
	mov	DWORD PTR _VgaBufferIndex, eax
; Line 324
	movsx	ecx, BYTE PTR _Color$[ebp]
	test	ecx, ecx
	jne	SHORT $LN3@SetCursorA
	mov	DWORD PTR tv70[ebp], 7
	jmp	SHORT $LN4@SetCursorA
$LN3@SetCursorA:
	movsx	edx, BYTE PTR _Color$[ebp]
	mov	DWORD PTR tv70[ebp], edx
$LN4@SetCursorA:
	movzx	eax, BYTE PTR tv70[ebp]
	mov	BYTE PTR _CurrentTextColor, al
; Line 325
	mov	esp, ebp
	pop	ebp
	ret	0
_SetCursorAndColor ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_ColumnX$ = 8						; size = 4
_RowY$ = 12						; size = 4
_SetCursorPosition PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 318
	push	ebp
	mov	ebp, esp
; Line 319
	imul	eax, DWORD PTR _RowY$[ebp], 80
	add	eax, DWORD PTR _ColumnX$[ebp]
	shl	eax, 1
	mov	DWORD PTR _VgaBufferIndex, eax
; Line 320
	pop	ebp
	ret	0
_SetCursorPosition ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_IntegerStringBuffer$1 = -148				; size = 12
_FloatValue$2 = -136					; size = 8
_DepthLimit$ = -128					; size = 4
_FractionalDecimalPart$3 = -124				; size = 8
tv237 = -116						; size = 4
tv198 = -112						; size = 4
tv151 = -108						; size = 4
_StringValue$4 = -104					; size = 4
_IntegerStringBuffer$5 = -100				; size = 12
_DidExpandString$ = -88					; size = 4
_Pass$6 = -84						; size = 4
_i$7 = -80						; size = 4
_IsFormatHandled$8 = -76				; size = 4
_DivisorValue$9 = -72					; size = 4
_j$10 = -68						; size = 4
_IntegerValue$11 = -64					; size = 4
_AbsoluteValue$12 = -60					; size = 4
_j$13 = -56						; size = 4
_FractionalPartAsInteger$14 = -52			; size = 4
_CopyIter$15 = -48					; size = 4
_WholeNumberPart$16 = -44				; size = 4
_InLen$ = -40						; size = 4
_BufferIterator$17 = -36				; size = 4
_j$18 = -32						; size = 4
_AbsoluteValue$19 = -28					; size = 4
_VariableArguments$ = -24				; size = 4
_OutBuf$ = -20						; size = 4
_InBuf$ = -16						; size = 4
_FormatStringIndex$20 = -12				; size = 4
_BufferIterator$21 = -8					; size = 4
_OutIndex$22 = -4					; size = 4
_FormatString$ = 8					; size = 4
_kprintf PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 166
	push	ebp
	mov	ebp, esp
	sub	esp, 148				; 00000094H
; Line 168
	lea	eax, DWORD PTR _FormatString$[ebp+4]
	mov	DWORD PTR _VariableArguments$[ebp], eax
; Line 170
	mov	DWORD PTR _InBuf$[ebp], 589824		; 00090000H
; Line 171
	mov	DWORD PTR _OutBuf$[ebp], 598016		; 00092000H
; Line 173
	mov	DWORD PTR _InLen$[ebp], 0
$LN2@kprintf:
; Line 174
	mov	ecx, DWORD PTR _FormatString$[ebp]
	add	ecx, DWORD PTR _InLen$[ebp]
	movsx	edx, BYTE PTR [ecx]
	test	edx, edx
	je	SHORT $LN3@kprintf
; Line 175
	mov	eax, DWORD PTR _InBuf$[ebp]
	add	eax, DWORD PTR _InLen$[ebp]
	mov	ecx, DWORD PTR _FormatString$[ebp]
	add	ecx, DWORD PTR _InLen$[ebp]
	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR [eax], dl
; Line 176
	mov	eax, DWORD PTR _InLen$[ebp]
	add	eax, 1
	mov	DWORD PTR _InLen$[ebp], eax
; Line 177
	jmp	SHORT $LN2@kprintf
$LN3@kprintf:
; Line 178
	mov	ecx, DWORD PTR _InBuf$[ebp]
	add	ecx, DWORD PTR _InLen$[ebp]
	mov	BYTE PTR [ecx], 0
; Line 180
	mov	DWORD PTR _DidExpandString$[ebp], 0
; Line 181
	mov	DWORD PTR _DepthLimit$[ebp], 6
; Line 183
	mov	DWORD PTR _Pass$6[ebp], 0
	jmp	SHORT $LN6@kprintf
$LN4@kprintf:
	mov	edx, DWORD PTR _Pass$6[ebp]
	add	edx, 1
	mov	DWORD PTR _Pass$6[ebp], edx
$LN6@kprintf:
	mov	eax, DWORD PTR _Pass$6[ebp]
	cmp	eax, DWORD PTR _DepthLimit$[ebp]
	jge	$LN5@kprintf
; Line 184
	mov	DWORD PTR _OutIndex$22[ebp], 0
; Line 185
	mov	DWORD PTR _DidExpandString$[ebp], 0
; Line 187
	mov	DWORD PTR _FormatStringIndex$20[ebp], 0
	jmp	SHORT $LN9@kprintf
$LN7@kprintf:
	mov	ecx, DWORD PTR _FormatStringIndex$20[ebp]
	add	ecx, 1
	mov	DWORD PTR _FormatStringIndex$20[ebp], ecx
$LN9@kprintf:
	mov	edx, DWORD PTR _InBuf$[ebp]
	add	edx, DWORD PTR _FormatStringIndex$20[ebp]
	movsx	eax, BYTE PTR [edx]
	test	eax, eax
	je	$LN8@kprintf
; Line 190
	mov	ecx, DWORD PTR _InBuf$[ebp]
	add	ecx, DWORD PTR _FormatStringIndex$20[ebp]
	movsx	edx, BYTE PTR [ecx]
	cmp	edx, 123				; 0000007bH
	jne	$LN48@kprintf
; Line 191
	mov	DWORD PTR _IsFormatHandled$8[ebp], 0
; Line 193
	push	OFFSET $SG30574
	mov	eax, DWORD PTR _FormatStringIndex$20[ebp]
	mov	ecx, DWORD PTR _InBuf$[ebp]
	lea	edx, DWORD PTR [ecx+eax+1]
	push	edx
	call	_IsSubstringMatch
	add	esp, 8
	test	eax, eax
	je	SHORT $LN37@kprintf
; Line 194
	mov	eax, DWORD PTR _VariableArguments$[ebp]
	add	eax, 4
	mov	DWORD PTR _VariableArguments$[ebp], eax
	mov	ecx, DWORD PTR _VariableArguments$[ebp]
	mov	edx, DWORD PTR [ecx-4]
	mov	DWORD PTR _StringValue$4[ebp], edx
; Line 195
	mov	DWORD PTR _j$13[ebp], 0
$LN10@kprintf:
; Line 196
	mov	eax, DWORD PTR _StringValue$4[ebp]
	add	eax, DWORD PTR _j$13[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	je	SHORT $LN11@kprintf
; Line 197
	mov	edx, DWORD PTR _OutBuf$[ebp]
	add	edx, DWORD PTR _OutIndex$22[ebp]
	mov	eax, DWORD PTR _StringValue$4[ebp]
	add	eax, DWORD PTR _j$13[ebp]
	mov	cl, BYTE PTR [eax]
	mov	BYTE PTR [edx], cl
	mov	edx, DWORD PTR _OutIndex$22[ebp]
	add	edx, 1
	mov	DWORD PTR _OutIndex$22[ebp], edx
	mov	eax, DWORD PTR _j$13[ebp]
	add	eax, 1
	mov	DWORD PTR _j$13[ebp], eax
; Line 198
	jmp	SHORT $LN10@kprintf
$LN11@kprintf:
; Line 199
	mov	DWORD PTR _IsFormatHandled$8[ebp], 1
; Line 200
	mov	DWORD PTR _DidExpandString$[ebp], 1
; Line 201
	jmp	$LN42@kprintf
$LN37@kprintf:
; Line 203
	push	OFFSET $SG30577
	mov	ecx, DWORD PTR _FormatStringIndex$20[ebp]
	mov	edx, DWORD PTR _InBuf$[ebp]
	lea	eax, DWORD PTR [edx+ecx+1]
	push	eax
	call	_IsSubstringMatch
	add	esp, 8
	test	eax, eax
	je	$LN39@kprintf
; Line 204
	mov	ecx, DWORD PTR _VariableArguments$[ebp]
	add	ecx, 4
	mov	DWORD PTR _VariableArguments$[ebp], ecx
	mov	edx, DWORD PTR _VariableArguments$[ebp]
	mov	eax, DWORD PTR [edx-4]
	mov	DWORD PTR _IntegerValue$11[ebp], eax
; Line 206
	mov	DWORD PTR _BufferIterator$17[ebp], 11	; 0000000bH
; Line 207
	mov	ecx, DWORD PTR _BufferIterator$17[ebp]
	mov	BYTE PTR _IntegerStringBuffer$1[ebp+ecx], 0
; Line 208
	cmp	DWORD PTR _IntegerValue$11[ebp], 0
	jge	SHORT $LN51@kprintf
	mov	edx, DWORD PTR _IntegerValue$11[ebp]
	neg	edx
	mov	DWORD PTR tv151[ebp], edx
	jmp	SHORT $LN52@kprintf
$LN51@kprintf:
	mov	eax, DWORD PTR _IntegerValue$11[ebp]
	mov	DWORD PTR tv151[ebp], eax
$LN52@kprintf:
	mov	ecx, DWORD PTR tv151[ebp]
	mov	DWORD PTR _AbsoluteValue$12[ebp], ecx
$LN14@kprintf:
; Line 210
	mov	edx, DWORD PTR _BufferIterator$17[ebp]
	sub	edx, 1
	mov	DWORD PTR _BufferIterator$17[ebp], edx
	mov	eax, DWORD PTR _AbsoluteValue$12[ebp]
	xor	edx, edx
	mov	ecx, 10					; 0000000aH
	div	ecx
	add	edx, 48					; 00000030H
	mov	eax, DWORD PTR _BufferIterator$17[ebp]
	mov	BYTE PTR _IntegerStringBuffer$1[ebp+eax], dl
; Line 211
	mov	eax, DWORD PTR _AbsoluteValue$12[ebp]
	xor	edx, edx
	mov	ecx, 10					; 0000000aH
	div	ecx
	mov	DWORD PTR _AbsoluteValue$12[ebp], eax
; Line 212
	cmp	DWORD PTR _AbsoluteValue$12[ebp], 0
	ja	SHORT $LN14@kprintf
; Line 213
	cmp	DWORD PTR _IntegerValue$11[ebp], 0
	jge	SHORT $LN41@kprintf
; Line 214
	mov	edx, DWORD PTR _BufferIterator$17[ebp]
	sub	edx, 1
	mov	DWORD PTR _BufferIterator$17[ebp], edx
	mov	eax, DWORD PTR _BufferIterator$17[ebp]
	mov	BYTE PTR _IntegerStringBuffer$1[ebp+eax], 45 ; 0000002dH
$LN41@kprintf:
; Line 216
	mov	ecx, DWORD PTR _BufferIterator$17[ebp]
	mov	DWORD PTR _j$10[ebp], ecx
$LN15@kprintf:
; Line 217
	mov	edx, DWORD PTR _j$10[ebp]
	movsx	eax, BYTE PTR _IntegerStringBuffer$1[ebp+edx]
	test	eax, eax
	je	SHORT $LN16@kprintf
; Line 218
	mov	ecx, DWORD PTR _OutBuf$[ebp]
	add	ecx, DWORD PTR _OutIndex$22[ebp]
	mov	edx, DWORD PTR _j$10[ebp]
	mov	al, BYTE PTR _IntegerStringBuffer$1[ebp+edx]
	mov	BYTE PTR [ecx], al
	mov	ecx, DWORD PTR _OutIndex$22[ebp]
	add	ecx, 1
	mov	DWORD PTR _OutIndex$22[ebp], ecx
	mov	edx, DWORD PTR _j$10[ebp]
	add	edx, 1
	mov	DWORD PTR _j$10[ebp], edx
; Line 219
	jmp	SHORT $LN15@kprintf
$LN16@kprintf:
; Line 220
	mov	DWORD PTR _IsFormatHandled$8[ebp], 1
; Line 221
	jmp	$LN42@kprintf
$LN39@kprintf:
; Line 223
	push	OFFSET $SG30580
	mov	eax, DWORD PTR _FormatStringIndex$20[ebp]
	mov	ecx, DWORD PTR _InBuf$[ebp]
	lea	edx, DWORD PTR [ecx+eax+1]
	push	edx
	call	_IsSubstringMatch
	add	esp, 8
	test	eax, eax
	je	$LN42@kprintf
; Line 224
	mov	eax, DWORD PTR _VariableArguments$[ebp]
	add	eax, 8
	mov	DWORD PTR _VariableArguments$[ebp], eax
	mov	ecx, DWORD PTR _VariableArguments$[ebp]
	movsd	xmm0, QWORD PTR [ecx-8]
	movsd	QWORD PTR _FloatValue$2[ebp], xmm0
; Line 226
	cvttsd2si edx, QWORD PTR _FloatValue$2[ebp]
	mov	DWORD PTR _WholeNumberPart$16[ebp], edx
; Line 227
	cvtsi2sd xmm0, DWORD PTR _WholeNumberPart$16[ebp]
	movsd	xmm1, QWORD PTR _FloatValue$2[ebp]
	subsd	xmm1, xmm0
	movsd	QWORD PTR _FractionalDecimalPart$3[ebp], xmm1
; Line 228
	xorps	xmm0, xmm0
	comisd	xmm0, QWORD PTR _FractionalDecimalPart$3[ebp]
	jbe	SHORT $LN43@kprintf
; Line 229
	movsd	xmm0, QWORD PTR _FractionalDecimalPart$3[ebp]
	xorps	xmm0, QWORD PTR __xmm@80000000000000008000000000000000
	movsd	QWORD PTR _FractionalDecimalPart$3[ebp], xmm0
$LN43@kprintf:
; Line 232
	xorps	xmm0, xmm0
	comisd	xmm0, QWORD PTR _FloatValue$2[ebp]
	jbe	SHORT $LN44@kprintf
	cmp	DWORD PTR _WholeNumberPart$16[ebp], 0
	jne	SHORT $LN44@kprintf
; Line 233
	mov	eax, DWORD PTR _OutBuf$[ebp]
	add	eax, DWORD PTR _OutIndex$22[ebp]
	mov	BYTE PTR [eax], 45			; 0000002dH
	mov	ecx, DWORD PTR _OutIndex$22[ebp]
	add	ecx, 1
	mov	DWORD PTR _OutIndex$22[ebp], ecx
$LN44@kprintf:
; Line 237
	mov	DWORD PTR _BufferIterator$21[ebp], 11	; 0000000bH
; Line 238
	mov	edx, DWORD PTR _BufferIterator$21[ebp]
	mov	BYTE PTR _IntegerStringBuffer$5[ebp+edx], 0
; Line 239
	cmp	DWORD PTR _WholeNumberPart$16[ebp], 0
	jge	SHORT $LN53@kprintf
	mov	eax, DWORD PTR _WholeNumberPart$16[ebp]
	neg	eax
	mov	DWORD PTR tv198[ebp], eax
	jmp	SHORT $LN54@kprintf
$LN53@kprintf:
	mov	ecx, DWORD PTR _WholeNumberPart$16[ebp]
	mov	DWORD PTR tv198[ebp], ecx
$LN54@kprintf:
	mov	edx, DWORD PTR tv198[ebp]
	mov	DWORD PTR _AbsoluteValue$19[ebp], edx
$LN19@kprintf:
; Line 241
	mov	eax, DWORD PTR _BufferIterator$21[ebp]
	sub	eax, 1
	mov	DWORD PTR _BufferIterator$21[ebp], eax
	mov	eax, DWORD PTR _AbsoluteValue$19[ebp]
	xor	edx, edx
	mov	ecx, 10					; 0000000aH
	div	ecx
	add	edx, 48					; 00000030H
	mov	eax, DWORD PTR _BufferIterator$21[ebp]
	mov	BYTE PTR _IntegerStringBuffer$5[ebp+eax], dl
; Line 242
	mov	eax, DWORD PTR _AbsoluteValue$19[ebp]
	xor	edx, edx
	mov	ecx, 10					; 0000000aH
	div	ecx
	mov	DWORD PTR _AbsoluteValue$19[ebp], eax
; Line 243
	cmp	DWORD PTR _AbsoluteValue$19[ebp], 0
	ja	SHORT $LN19@kprintf
; Line 244
	cmp	DWORD PTR _WholeNumberPart$16[ebp], 0
	jge	SHORT $LN45@kprintf
; Line 245
	mov	edx, DWORD PTR _BufferIterator$21[ebp]
	sub	edx, 1
	mov	DWORD PTR _BufferIterator$21[ebp], edx
	mov	eax, DWORD PTR _BufferIterator$21[ebp]
	mov	BYTE PTR _IntegerStringBuffer$5[ebp+eax], 45 ; 0000002dH
$LN45@kprintf:
; Line 247
	mov	ecx, DWORD PTR _BufferIterator$21[ebp]
	mov	DWORD PTR _j$18[ebp], ecx
$LN20@kprintf:
; Line 248
	mov	edx, DWORD PTR _j$18[ebp]
	movsx	eax, BYTE PTR _IntegerStringBuffer$5[ebp+edx]
	test	eax, eax
	je	SHORT $LN21@kprintf
; Line 249
	mov	ecx, DWORD PTR _OutBuf$[ebp]
	add	ecx, DWORD PTR _OutIndex$22[ebp]
	mov	edx, DWORD PTR _j$18[ebp]
	mov	al, BYTE PTR _IntegerStringBuffer$5[ebp+edx]
	mov	BYTE PTR [ecx], al
	mov	ecx, DWORD PTR _OutIndex$22[ebp]
	add	ecx, 1
	mov	DWORD PTR _OutIndex$22[ebp], ecx
	mov	edx, DWORD PTR _j$18[ebp]
	add	edx, 1
	mov	DWORD PTR _j$18[ebp], edx
; Line 250
	jmp	SHORT $LN20@kprintf
$LN21@kprintf:
; Line 252
	mov	eax, DWORD PTR _OutBuf$[ebp]
	add	eax, DWORD PTR _OutIndex$22[ebp]
	mov	BYTE PTR [eax], 46			; 0000002eH
	mov	ecx, DWORD PTR _OutIndex$22[ebp]
	add	ecx, 1
	mov	DWORD PTR _OutIndex$22[ebp], ecx
; Line 254
	movsd	xmm0, QWORD PTR _FractionalDecimalPart$3[ebp]
	mulsd	xmm0, QWORD PTR __real@40c3880000000000
	cvttsd2si edx, xmm0
	mov	DWORD PTR _FractionalPartAsInteger$14[ebp], edx
; Line 255
	mov	DWORD PTR _DivisorValue$9[ebp], 1000	; 000003e8H
$LN22@kprintf:
; Line 256
	cmp	DWORD PTR _DivisorValue$9[ebp], 1
	jle	SHORT $LN23@kprintf
; Line 257
	mov	eax, DWORD PTR _FractionalPartAsInteger$14[ebp]
	cmp	eax, DWORD PTR _DivisorValue$9[ebp]
	jge	SHORT $LN46@kprintf
; Line 258
	mov	ecx, DWORD PTR _OutBuf$[ebp]
	add	ecx, DWORD PTR _OutIndex$22[ebp]
	mov	BYTE PTR [ecx], 48			; 00000030H
	mov	edx, DWORD PTR _OutIndex$22[ebp]
	add	edx, 1
	mov	DWORD PTR _OutIndex$22[ebp], edx
$LN46@kprintf:
; Line 260
	mov	eax, DWORD PTR _DivisorValue$9[ebp]
	cdq
	mov	ecx, 10					; 0000000aH
	idiv	ecx
	mov	DWORD PTR _DivisorValue$9[ebp], eax
; Line 261
	jmp	SHORT $LN22@kprintf
$LN23@kprintf:
; Line 263
	mov	DWORD PTR _BufferIterator$21[ebp], 11	; 0000000bH
; Line 264
	mov	edx, DWORD PTR _BufferIterator$21[ebp]
	mov	BYTE PTR _IntegerStringBuffer$5[ebp+edx], 0
; Line 265
	cmp	DWORD PTR _FractionalPartAsInteger$14[ebp], 0
	jge	SHORT $LN55@kprintf
	mov	eax, DWORD PTR _FractionalPartAsInteger$14[ebp]
	neg	eax
	mov	DWORD PTR tv237[ebp], eax
	jmp	SHORT $LN56@kprintf
$LN55@kprintf:
	mov	ecx, DWORD PTR _FractionalPartAsInteger$14[ebp]
	mov	DWORD PTR tv237[ebp], ecx
$LN56@kprintf:
	mov	edx, DWORD PTR tv237[ebp]
	mov	DWORD PTR _AbsoluteValue$19[ebp], edx
$LN26@kprintf:
; Line 267
	mov	eax, DWORD PTR _BufferIterator$21[ebp]
	sub	eax, 1
	mov	DWORD PTR _BufferIterator$21[ebp], eax
	mov	eax, DWORD PTR _AbsoluteValue$19[ebp]
	xor	edx, edx
	mov	ecx, 10					; 0000000aH
	div	ecx
	add	edx, 48					; 00000030H
	mov	eax, DWORD PTR _BufferIterator$21[ebp]
	mov	BYTE PTR _IntegerStringBuffer$5[ebp+eax], dl
; Line 268
	mov	eax, DWORD PTR _AbsoluteValue$19[ebp]
	xor	edx, edx
	mov	ecx, 10					; 0000000aH
	div	ecx
	mov	DWORD PTR _AbsoluteValue$19[ebp], eax
; Line 269
	cmp	DWORD PTR _AbsoluteValue$19[ebp], 0
	ja	SHORT $LN26@kprintf
; Line 270
	cmp	DWORD PTR _FractionalPartAsInteger$14[ebp], 0
	jge	SHORT $LN47@kprintf
; Line 271
	mov	edx, DWORD PTR _BufferIterator$21[ebp]
	sub	edx, 1
	mov	DWORD PTR _BufferIterator$21[ebp], edx
	mov	eax, DWORD PTR _BufferIterator$21[ebp]
	mov	BYTE PTR _IntegerStringBuffer$5[ebp+eax], 45 ; 0000002dH
$LN47@kprintf:
; Line 273
	mov	ecx, DWORD PTR _BufferIterator$21[ebp]
	mov	DWORD PTR _j$18[ebp], ecx
$LN27@kprintf:
; Line 274
	mov	edx, DWORD PTR _j$18[ebp]
	movsx	eax, BYTE PTR _IntegerStringBuffer$5[ebp+edx]
	test	eax, eax
	je	SHORT $LN28@kprintf
; Line 275
	mov	ecx, DWORD PTR _OutBuf$[ebp]
	add	ecx, DWORD PTR _OutIndex$22[ebp]
	mov	edx, DWORD PTR _j$18[ebp]
	mov	al, BYTE PTR _IntegerStringBuffer$5[ebp+edx]
	mov	BYTE PTR [ecx], al
	mov	ecx, DWORD PTR _OutIndex$22[ebp]
	add	ecx, 1
	mov	DWORD PTR _OutIndex$22[ebp], ecx
	mov	edx, DWORD PTR _j$18[ebp]
	add	edx, 1
	mov	DWORD PTR _j$18[ebp], edx
; Line 276
	jmp	SHORT $LN27@kprintf
$LN28@kprintf:
; Line 278
	mov	DWORD PTR _IsFormatHandled$8[ebp], 1
$LN42@kprintf:
; Line 283
	cmp	DWORD PTR _IsFormatHandled$8[ebp], 0
	je	SHORT $LN48@kprintf
$LN29@kprintf:
; Line 284
	mov	eax, DWORD PTR _InBuf$[ebp]
	add	eax, DWORD PTR _FormatStringIndex$20[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	je	SHORT $LN30@kprintf
	mov	edx, DWORD PTR _InBuf$[ebp]
	add	edx, DWORD PTR _FormatStringIndex$20[ebp]
	movsx	eax, BYTE PTR [edx]
	cmp	eax, 125				; 0000007dH
	je	SHORT $LN30@kprintf
; Line 285
	mov	ecx, DWORD PTR _FormatStringIndex$20[ebp]
	add	ecx, 1
	mov	DWORD PTR _FormatStringIndex$20[ebp], ecx
; Line 286
	jmp	SHORT $LN29@kprintf
$LN30@kprintf:
; Line 287
	jmp	$LN7@kprintf
$LN48@kprintf:
; Line 292
	mov	edx, DWORD PTR _OutBuf$[ebp]
	add	edx, DWORD PTR _OutIndex$22[ebp]
	mov	eax, DWORD PTR _InBuf$[ebp]
	add	eax, DWORD PTR _FormatStringIndex$20[ebp]
	mov	cl, BYTE PTR [eax]
	mov	BYTE PTR [edx], cl
	mov	edx, DWORD PTR _OutIndex$22[ebp]
	add	edx, 1
	mov	DWORD PTR _OutIndex$22[ebp], edx
; Line 293
	jmp	$LN7@kprintf
$LN8@kprintf:
; Line 294
	mov	eax, DWORD PTR _OutBuf$[ebp]
	add	eax, DWORD PTR _OutIndex$22[ebp]
	mov	BYTE PTR [eax], 0
; Line 296
	cmp	DWORD PTR _DidExpandString$[ebp], 0
	jne	SHORT $LN49@kprintf
; Line 297
	jmp	SHORT $LN5@kprintf
$LN49@kprintf:
; Line 300
	mov	DWORD PTR _CopyIter$15[ebp], 0
$LN31@kprintf:
; Line 301
	mov	ecx, DWORD PTR _OutBuf$[ebp]
	add	ecx, DWORD PTR _CopyIter$15[ebp]
	movsx	edx, BYTE PTR [ecx]
	test	edx, edx
	je	SHORT $LN32@kprintf
; Line 302
	mov	eax, DWORD PTR _InBuf$[ebp]
	add	eax, DWORD PTR _CopyIter$15[ebp]
	mov	ecx, DWORD PTR _OutBuf$[ebp]
	add	ecx, DWORD PTR _CopyIter$15[ebp]
	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR [eax], dl
; Line 303
	mov	eax, DWORD PTR _CopyIter$15[ebp]
	add	eax, 1
	mov	DWORD PTR _CopyIter$15[ebp], eax
; Line 304
	jmp	SHORT $LN31@kprintf
$LN32@kprintf:
; Line 305
	mov	ecx, DWORD PTR _InBuf$[ebp]
	add	ecx, DWORD PTR _CopyIter$15[ebp]
	mov	BYTE PTR [ecx], 0
; Line 306
	jmp	$LN4@kprintf
$LN5@kprintf:
; Line 308
	mov	edx, DWORD PTR _OutBuf$[ebp]
	push	edx
	call	_kprint
	add	esp, 4
; Line 310
	mov	DWORD PTR _i$7[ebp], 0
	jmp	SHORT $LN35@kprintf
$LN33@kprintf:
	mov	eax, DWORD PTR _i$7[ebp]
	add	eax, 1
	mov	DWORD PTR _i$7[ebp], eax
$LN35@kprintf:
	cmp	DWORD PTR _i$7[ebp], 16384		; 00004000H
	jge	SHORT $LN34@kprintf
; Line 311
	mov	ecx, DWORD PTR _i$7[ebp]
	mov	BYTE PTR [ecx+589824], 0
; Line 312
	jmp	SHORT $LN33@kprintf
$LN34@kprintf:
; Line 313
	mov	esp, ebp
	pop	ebp
	ret	0
_kprintf ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_Index$ = -4						; size = 4
_SourceString$ = 8					; size = 4
_PatternString$ = 12					; size = 4
_IsSubstringMatch PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 151
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 152
	mov	DWORD PTR _Index$[ebp], 0
$LN2@IsSubstrin:
; Line 153
	mov	eax, DWORD PTR _PatternString$[ebp]
	add	eax, DWORD PTR _Index$[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	je	SHORT $LN3@IsSubstrin
; Line 154
	mov	edx, DWORD PTR _SourceString$[ebp]
	add	edx, DWORD PTR _Index$[ebp]
	movsx	eax, BYTE PTR [edx]
	mov	ecx, DWORD PTR _PatternString$[ebp]
	add	ecx, DWORD PTR _Index$[ebp]
	movsx	edx, BYTE PTR [ecx]
	cmp	eax, edx
	je	SHORT $LN4@IsSubstrin
; Line 155
	xor	eax, eax
	jmp	SHORT $LN1@IsSubstrin
$LN4@IsSubstrin:
; Line 157
	mov	eax, DWORD PTR _Index$[ebp]
	add	eax, 1
	mov	DWORD PTR _Index$[ebp], eax
; Line 158
	jmp	SHORT $LN2@IsSubstrin
$LN3@IsSubstrin:
; Line 159
	mov	eax, 1
$LN1@IsSubstrin:
; Line 160
	mov	esp, ebp
	pop	ebp
	ret	0
_IsSubstringMatch ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_IntegerStringBuffer$ = -24				; size = 12
tv68 = -12						; size = 4
_AbsoluteValue$ = -8					; size = 4
_BufferIterator$ = -4					; size = 4
_IntegerValue$ = 8					; size = 4
_kprint_int PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 128
	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
; Line 130
	mov	DWORD PTR _BufferIterator$[ebp], 11	; 0000000bH
; Line 131
	mov	eax, DWORD PTR _BufferIterator$[ebp]
	mov	BYTE PTR _IntegerStringBuffer$[ebp+eax], 0
; Line 133
	cmp	DWORD PTR _IntegerValue$[ebp], 0
	jge	SHORT $LN7@kprint_int
	mov	ecx, DWORD PTR _IntegerValue$[ebp]
	neg	ecx
	mov	DWORD PTR tv68[ebp], ecx
	jmp	SHORT $LN8@kprint_int
$LN7@kprint_int:
	mov	edx, DWORD PTR _IntegerValue$[ebp]
	mov	DWORD PTR tv68[ebp], edx
$LN8@kprint_int:
	mov	eax, DWORD PTR tv68[ebp]
	mov	DWORD PTR _AbsoluteValue$[ebp], eax
$LN4@kprint_int:
; Line 136
	mov	ecx, DWORD PTR _BufferIterator$[ebp]
	sub	ecx, 1
	mov	DWORD PTR _BufferIterator$[ebp], ecx
	mov	eax, DWORD PTR _AbsoluteValue$[ebp]
	xor	edx, edx
	mov	ecx, 10					; 0000000aH
	div	ecx
	add	edx, 48					; 00000030H
	mov	eax, DWORD PTR _BufferIterator$[ebp]
	mov	BYTE PTR _IntegerStringBuffer$[ebp+eax], dl
; Line 137
	mov	eax, DWORD PTR _AbsoluteValue$[ebp]
	xor	edx, edx
	mov	ecx, 10					; 0000000aH
	div	ecx
	mov	DWORD PTR _AbsoluteValue$[ebp], eax
; Line 138
	cmp	DWORD PTR _AbsoluteValue$[ebp], 0
	ja	SHORT $LN4@kprint_int
; Line 140
	cmp	DWORD PTR _IntegerValue$[ebp], 0
	jge	SHORT $LN5@kprint_int
	cmp	DWORD PTR _NothingToSeeHere, 1
	jne	SHORT $LN5@kprint_int
; Line 141
	mov	edx, DWORD PTR _BufferIterator$[ebp]
	sub	edx, 1
	mov	DWORD PTR _BufferIterator$[ebp], edx
	mov	eax, DWORD PTR _BufferIterator$[ebp]
	mov	BYTE PTR _IntegerStringBuffer$[ebp+eax], 45 ; 0000002dH
$LN5@kprint_int:
; Line 144
	mov	ecx, DWORD PTR _BufferIterator$[ebp]
	lea	edx, DWORD PTR _IntegerStringBuffer$[ebp+ecx]
	push	edx
	call	_kprint
	add	esp, 4
; Line 145
	mov	esp, ebp
	pop	ebp
	ret	0
_kprint_int ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv67 = -1						; size = 1
_StringValue$ = 8					; size = 4
_kprint	PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 118
	push	ebp
	mov	ebp, esp
	push	ecx
$LN2@kprint:
; Line 119
	mov	eax, DWORD PTR _StringValue$[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	je	SHORT $LN3@kprint
; Line 120
	mov	edx, DWORD PTR _StringValue$[ebp]
	mov	al, BYTE PTR [edx]
	mov	BYTE PTR tv67[ebp], al
	movzx	ecx, BYTE PTR tv67[ebp]
	push	ecx
	call	_KernelPrintCharacter
	add	esp, 4
	mov	edx, DWORD PTR _StringValue$[ebp]
	add	edx, 1
	mov	DWORD PTR _StringValue$[ebp], edx
; Line 121
	jmp	SHORT $LN2@kprint
$LN3@kprint:
; Line 122
	mov	esp, ebp
	pop	ebp
	ret	0
_kprint	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_CharacterToPrint$ = 8					; size = 1
_KernelPrintCharacter PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 105
	push	ebp
	mov	ebp, esp
; Line 106
	movsx	eax, BYTE PTR _CharacterToPrint$[ebp]
	cmp	eax, 10					; 0000000aH
	jne	SHORT $LN2@KernelPrin
; Line 107
	mov	eax, DWORD PTR _VgaBufferIndex
	cdq
	mov	ecx, 160				; 000000a0H
	idiv	ecx
	mov	eax, 160				; 000000a0H
	sub	eax, edx
	add	eax, DWORD PTR _VgaBufferIndex
	mov	DWORD PTR _VgaBufferIndex, eax
; Line 108
	jmp	SHORT $LN3@KernelPrin
$LN2@KernelPrin:
; Line 109
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _VgaBufferIndex
	mov	dl, BYTE PTR _CharacterToPrint$[ebp]
	mov	BYTE PTR [ecx], dl
	mov	eax, DWORD PTR _VgaBufferIndex
	add	eax, 1
	mov	DWORD PTR _VgaBufferIndex, eax
; Line 110
	mov	ecx, DWORD PTR _VgaMemoryAddress
	add	ecx, DWORD PTR _VgaBufferIndex
	mov	dl, BYTE PTR _CurrentTextColor
	mov	BYTE PTR [ecx], dl
	mov	eax, DWORD PTR _VgaBufferIndex
	add	eax, 1
	mov	DWORD PTR _VgaBufferIndex, eax
$LN3@KernelPrin:
; Line 112
	pop	ebp
	ret	0
_KernelPrintCharacter ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_KillACertainPolititianThatIsA$1 = -60			; size = 4
_NavCmdStartX$2 = -56					; size = 4
_NavCmdStartY$3 = -52					; size = 4
_CedBaseLine$4 = -48					; size = 4
_InsertTimer$5 = -44					; size = 4
_InsertHeld$6 = -40					; size = 4
_BitCount$7 = -36					; size = 4
_OvertypeMode$8 = -32					; size = 4
_ActiveBox$9 = -28					; size = 4
_RightY$10 = -24					; size = 4
_RightX$11 = -20					; size = 4
_LeftY$12 = -16						; size = 4
_LeftX$13 = -12						; size = 4
_LOCATORofFUNCTIONS$14 = -8				; size = 4
_EnableTheAncientChaosGods$15 = -4			; size = 4
_NothingElseToSeeHere PROC
; File C:\Users\DELL\Downloads\nasm-2.16.01-win64\nasm-2.16.01\32bit\ANNDOS\BINARY OS\kernel.c
; Line 80
	push	ebp
	mov	ebp, esp
	sub	esp, 60					; 0000003cH
; Line 81
	cmp	DWORD PTR _NothingToSeeHere, 1
	je	SHORT $LN3@NothingEls
; Line 82
	mov	DWORD PTR _EnableTheAncientChaosGods$15[ebp], 1
; Line 83
	cmp	DWORD PTR _EnableTheAncientChaosGods$15[ebp], 1
	jne	SHORT $LN3@NothingEls
	cmp	DWORD PTR _NothingToSeeHere, 1
	je	SHORT $LN3@NothingEls
; Line 84
	mov	DWORD PTR _LOCATORofFUNCTIONS$14[ebp], OFFSET $SG30445
; Line 85
	mov	DWORD PTR _LeftX$13[ebp], 256		; 00000100H
	mov	DWORD PTR _LeftY$12[ebp], 3
; Line 86
	mov	DWORD PTR _RightX$11[ebp], 589		; 0000024dH
	mov	DWORD PTR _RightY$10[ebp], 9
; Line 87
	mov	DWORD PTR _ActiveBox$9[ebp], 32		; 00000020H
; Line 88
	mov	DWORD PTR _OvertypeMode$8[ebp], 999693	; 000f410dH
; Line 89
	mov	DWORD PTR _BitCount$7[ebp], 83		; 00000053H
; Line 90
	mov	DWORD PTR _InsertHeld$6[ebp], -70382155	; fbce0db5H
; Line 91
	mov	DWORD PTR _InsertTimer$5[ebp], 89	; 00000059H
; Line 92
	mov	DWORD PTR _CedBaseLine$4[ebp], 69	; 00000045H
; Line 93
	mov	DWORD PTR _NavCmdStartY$3[ebp], 420	; 000001a4H
; Line 94
	mov	DWORD PTR _NavCmdStartX$2[ebp], 133759342 ; 07f9016eH
; Line 95
	mov	DWORD PTR _KillACertainPolititianThatIsA$1[ebp], OFFSET $SG30446
$LN3@NothingEls:
; Line 98
	mov	esp, ebp
	pop	ebp
	ret	0
_NothingElseToSeeHere ENDP
_TEXT	ENDS
END
